mod base16;
mod base16_relax;
mod black_white;
mod blackout;
mod everforest;
mod imperial;
mod materialdark;
mod monekai;
mod monochrome;
mod nord;
mod ocean;
mod oxocarbon;
mod radium;
mod reds;
mod rust;
mod shell;
mod solarized;
mod tundra;
mod vscodedark;

pub use base16::BASE16;
pub use base16_relax::BASE16_RELAX;
pub use black_white::BLACK_WHITE;
pub use blackout::BLACKOUT;
pub use everforest::EVERFOREST;
pub use imperial::IMPERIAL;
pub use materialdark::MATERIALDARK;
pub use monekai::MONEKAI;
pub use monochrome::MONOCHROME;
pub use nord::NORD;
pub use ocean::OCEAN;
pub use oxocarbon::OXOCARBON;
pub use radium::RADIUM;
pub use reds::REDS;
pub use rust::RUST;
pub use shell::SHELL;
pub use solarized::SOLARIZED;
pub use tundra::TUNDRA;
pub use vscodedark::VSCODEDARK;
