use std::borrow::Cow;
use crate::palette::{Colors, Palette, define_alias};

const DARKNESS: u8 = 63;

/// EverForest
/// Credits to original https://github.com/sainnhe/everforest
pub const EVERFOREST_LIGHT: Palette = Palette {
    theme_name: Cow::Borrowed("EverForest Light"), 
    theme: Cow::Borrowed("Light"), 
    name: Cow::Borrowed("EverForest"), 
    doc: Cow::Borrowed("Credits to original https://github.com/sainnhe/everforest"), 
    generator: Cow::Borrowed("light-dark:63"), 

    color: [
        Palette::interpolate2(0xd8d4cb, 0xfcf8ef, 0x0, 0x0),
        Palette::interpolate2(0x090a09, 0x2c2d2a, 0x0, 0x0),
        Palette::interpolate(0x5b738c, 0x8fa7bf, DARKNESS),
        Palette::interpolate(0x4e565c, 0x656d73, DARKNESS),
        Palette::interpolate(0xeddec2, 0xc4ac7b, DARKNESS),
        Palette::interpolate(0x272f35, 0x30383d, DARKNESS),
        Palette::interpolate(0x4e565c, 0x656d73, DARKNESS),
        Palette::interpolate(0xe67e80, 0xfc8f93, DARKNESS),
        Palette::interpolate(0xe69875, 0xf4ab8b, DARKNESS),
        Palette::interpolate(0xceb077, 0xddc187, DARKNESS),
        Palette::interpolate(0x9eb579, 0xb8ce94, DARKNESS),
        Palette::interpolate(0x75aa82, 0x83c092, DARKNESS),
        Palette::interpolate(0x5e938c, 0x77ada6, DARKNESS),
        Palette::interpolate(0x80b2ab, 0xafdbd5, DARKNESS),
        Palette::interpolate(0x7393b3, 0x8fa7bf, DARKNESS),
        Palette::interpolate(0x6fa59e, 0x8dc4bd, DARKNESS),
        Palette::interpolate(0xcb92ae, 0xe5b7cd, DARKNESS),
        Palette::interpolate(0xc45a7b, 0xf5608e, DARKNESS),
        Palette::interpolate(0x965e6e, 0xbf7082, DARKNESS),
    ],
    // must be sorted!
    aliased: Cow::Borrowed(&[
        define_alias("button-base.bg", Colors::White, 2),
        define_alias("container-arrow.fg", Colors::Gray, 1),
        define_alias("container-base.bg", Colors::BlueGreen, 0),
        define_alias("container-border.fg", Colors::Gray, 1),
        define_alias("dialog-arrow.fg", Colors::Gray, 1),
        define_alias("dialog-base.bg", Colors::Cyan, 0),
        define_alias("dialog-border.fg", Colors::Gray, 1),
        define_alias("disabled.bg", Colors::Gray, 2),
        define_alias("document-arrow.fg", Colors::Gray, 1),
        define_alias("document-base.bg", Colors::BlueGreen, 2),
        define_alias("document-border.fg", Colors::Gray, 1),
        define_alias("focus.bg", Colors::Primary, 1),
        define_alias("footer.bg", Colors::DeepBlue, 1),
        define_alias("footer.fg", Colors::DeepBlue, 7),
        define_alias("header.bg", Colors::DeepBlue, 1),
        define_alias("header.fg", Colors::DeepBlue, 7),
        define_alias("hover.bg", Colors::DeepBlue, 3),
        define_alias("input-focus.bg", Colors::Primary, 2),
        define_alias("input-select.bg", Colors::Secondary, 1),
        define_alias("input.bg", Colors::White, 0),
        define_alias("invalid.bg", Colors::Red, 1),
        define_alias("key-binding.bg", Colors::White, 3),
        define_alias("label.fg", Colors::TextDark, 1),
        define_alias("md+hidden", Colors::None, 0),
        define_alias("menu-base.bg", Colors::DeepBlue, 1),
        define_alias("month-header.fg", Colors::TextDark, 0),
        define_alias("popup-arrow.fg", Colors::Gray, 2),
        define_alias("popup-base.bg", Colors::White, 2),
        define_alias("popup-border.fg", Colors::Gray, 2),
        define_alias("select.bg", Colors::Secondary, 1),
        define_alias("shadow.bg", Colors::Black, 0),
        define_alias("status-base.bg", Colors::DeepBlue, 1),
        define_alias("title.bg", Colors::Green, 1),
        define_alias("title.fg", Colors::Green, 4),
        define_alias("week-header.fg", Colors::Gray, 0),
    ]),
};

