use crate::palette::{Colors, Palette, define_alias};
use std::borrow::Cow;

/// SunriseBreeze Light
const DARKNESS: u8 = 63;

pub const SUNRISEBREEZE_LIGHT: Palette = Palette {
    theme_name: Cow::Borrowed("SunriseBreeze Light"),
    theme: Cow::Borrowed("Light"),
    name: Cow::Borrowed("SunriseBreeze"),
    doc: Cow::Borrowed(""),
    generator: Cow::Borrowed("light-dark:63"),

    color: [
        Palette::interpolate2(0xebebeb, 0xffffff, 0x0, 0x0),
        Palette::interpolate2(0x0d0f11, 0x191919, 0x0, 0x0),
        Palette::interpolate(0x0969da, 0x0c7dff, DARKNESS),
        Palette::interpolate(0x2c9ab7, 0x2c9ab7, DARKNESS),
        Palette::interpolate(0xebebeb, 0xe0e0e0, DARKNESS),
        Palette::interpolate(0x1b1f23, 0x242424, DARKNESS),
        Palette::interpolate(0xa7b4b7, 0x74797f, DARKNESS),
        Palette::interpolate(0xd64545, 0xd64545, DARKNESS),
        Palette::interpolate(0xd9822b, 0xd9822b, DARKNESS),
        Palette::interpolate(0xbb8009, 0xbb8009, DARKNESS),
        Palette::interpolate(0x2ea043, 0x2ea043, DARKNESS),
        Palette::interpolate(0x238636, 0x238636, DARKNESS),
        Palette::interpolate(0x2c9ab7, 0x2c9ab7, DARKNESS),
        Palette::interpolate(0x2c9ab7, 0x2c9ab7, DARKNESS),
        Palette::interpolate(0x0969da, 0x0969da, DARKNESS),
        Palette::interpolate(0x0969da, 0x0969da, DARKNESS),
        Palette::interpolate(0x6f4ecf, 0x6f4ecf, DARKNESS),
        Palette::interpolate(0xf29999, 0xf29999, DARKNESS),
        Palette::interpolate(0xe87c7c, 0xe87c7c, DARKNESS),
    ],
    // must be sorted!
    aliased: Cow::Borrowed(&[
        define_alias("button-base.bg", Colors::Gray, 2),
        define_alias("container-arrow.fg", Colors::Primary, 7),
        define_alias("container-base.bg", Colors::Gray, 1),
        define_alias("container-border.fg", Colors::Primary, 7),
        define_alias("dialog-arrow.fg", Colors::Gray, 6),
        define_alias("dialog-base.bg", Colors::Gray, 0),
        define_alias("dialog-border.fg", Colors::Gray, 6),
        define_alias("disabled.bg", Colors::Gray, 3),
        define_alias("document-arrow.fg", Colors::Primary, 7),
        define_alias("document-base.bg", Colors::Gray, 0),
        define_alias("document-border.fg", Colors::Primary, 7),
        define_alias("focus.bg", Colors::Primary, 1),
        define_alias("footer.bg", Colors::Blue, 4),
        define_alias("footer.fg", Colors::TextLight, 0),
        define_alias("header.bg", Colors::Blue, 4),
        define_alias("header.fg", Colors::TextLight, 0),
        define_alias("hover.bg", Colors::Primary, 3),
        define_alias("input-focus.bg", Colors::Primary, 1),
        define_alias("input-select.bg", Colors::Secondary, 1),
        define_alias("input.bg", Colors::Gray, 3),
        define_alias("invalid.bg", Colors::Red, 0),
        define_alias("key-binding.bg", Colors::BlueGreen, 1),
        define_alias("label.fg", Colors::TextDark, 0),
        define_alias("md+hidden", Colors::None, 0),
        define_alias("menu-base.bg", Colors::Gray, 0),
        define_alias("month-header.fg", Colors::Primary, 7),
        define_alias("popup-arrow.fg", Colors::Gray, 1),
        define_alias("popup-base.bg", Colors::White, 0),
        define_alias("popup-border.fg", Colors::Gray, 1),
        define_alias("select.bg", Colors::Secondary, 0),
        define_alias("shadow.bg", Colors::TextDark, 0),
        define_alias("status-base.bg", Colors::Gray, 0),
        define_alias("title.bg", Colors::Blue, 4),
        define_alias("title.fg", Colors::TextLight, 0),
        define_alias("week-header.fg", Colors::Secondary, 7),
    ]),
};
