use crate::{ColorIdx, Colors, Palette};

/// Base16
const DARKNESS: u8 = 63;

pub const BASE16: Palette = Palette {
    name: "Base16", 

    color: [
        Palette::interpolate2(0xaaaaaa, 0xffffff, 0x0, 0x0),
        Palette::interpolate2(0x000000, 0x555555, 0x0, 0x0),
        Palette::interpolate(0x00aaaa, 0x00aaaa, DARKNESS),
        Palette::interpolate(0x00aa00, 0x00aa00, DARKNESS),
        Palette::interpolate(0xaaaaaa, 0xffffff, DARKNESS),
        Palette::interpolate(0x000000, 0x555555, DARKNESS),
        Palette::interpolate(0x555555, 0xaaaaaa, DARKNESS),
        Palette::interpolate(0xaa0000, 0xaa0000, DARKNESS),
        Palette::interpolate(0xaa5500, 0xaa5500, DARKNESS),
        Palette::interpolate(0xffff55, 0xffff55, DARKNESS),
        Palette::interpolate(0x55ff55, 0x55ff55, DARKNESS),
        Palette::interpolate(0x00aa00, 0x00aa00, DARKNESS),
        Palette::interpolate(0x55ffff, 0x55ffff, DARKNESS),
        Palette::interpolate(0x00aaaa, 0x00aaaa, DARKNESS),
        Palette::interpolate(0x5555ff, 0x5555ff, DARKNESS),
        Palette::interpolate(0x0000af, 0x0000af, DARKNESS),
        Palette::interpolate(0xaa00aa, 0xaa00aa, DARKNESS),
        Palette::interpolate(0xff55ff, 0xff55ff, DARKNESS),
        Palette::interpolate(0xff5555, 0xff5a55, DARKNESS),
    ],
    // must be sorted!
    aliased: &[
        ("button-base.bg", ColorIdx(Colors::Gray, 0)),
        ("container-arrow.fg", ColorIdx(Colors::None, 0)),
        ("container-base.bg", ColorIdx(Colors::Black, 0)),
        ("container-border.fg", ColorIdx(Colors::None, 0)),
        ("dialog-arrow.fg", ColorIdx(Colors::None, 0)),
        ("dialog-base.bg", ColorIdx(Colors::Gray, 0)),
        ("dialog-border.fg", ColorIdx(Colors::None, 0)),
        ("disabled.bg", ColorIdx(Colors::Gray, 3)),
        ("document", ColorIdx(Colors::None, 0)),
        ("focus.bg", ColorIdx(Colors::Primary, 0)),
        ("footer.bg", ColorIdx(Colors::None, 0)),
        ("footer.fg", ColorIdx(Colors::Blue, 0)),
        ("header.bg", ColorIdx(Colors::None, 0)),
        ("header.fg", ColorIdx(Colors::Blue, 0)),
        ("heading-1", ColorIdx(Colors::None, 0)),
        ("heading-2", ColorIdx(Colors::None, 0)),
        ("hover.bg", ColorIdx(Colors::Secondary, 0)),
        ("input.bg", ColorIdx(Colors::Gray, 3)),
        ("invalid.bg", ColorIdx(Colors::Red, 0)),
        ("key-binding.bg", ColorIdx(Colors::Orange, 0)),
        ("label.fg", ColorIdx(Colors::White, 0)),
        ("menu-base.bg", ColorIdx(Colors::Black, 0)),
        ("month-header.fg", ColorIdx(Colors::Gray, 0)),
        ("popup-arrow.fg", ColorIdx(Colors::None, 0)),
        ("popup-base.bg", ColorIdx(Colors::White, 0)),
        ("popup-border.fg", ColorIdx(Colors::None, 0)),
        ("select.bg", ColorIdx(Colors::Secondary, 0)),
        ("shadow.bg", ColorIdx(Colors::Black, 0)),
        ("status-base.bg", ColorIdx(Colors::Black, 0)),
        ("sub-form", ColorIdx(Colors::None, 0)),
        ("text-focus.bg", ColorIdx(Colors::Primary, 0)),
        ("text-select.bg", ColorIdx(Colors::Secondary, 0)),
        ("title.bg", ColorIdx(Colors::Red, 0)),
        ("title.fg", ColorIdx(Colors::TextLight, 0)),
        ("week-header.fg", ColorIdx(Colors::Gray, 0)),
    ],
};

