use crate::{ColorIdx, Colors, Palette};

/// Base16
const DARKNESS: u8 = 63;

pub const BASE16: Palette = Palette {
    name: "Base16", 

    color: [
        Palette::interpolate2(0xaaaaaa, 0xffffff, 0x0, 0x0),
        Palette::interpolate2(0x000000, 0x555555, 0x0, 0x0),
        Palette::interpolate(0x00aaaa, 0x00aaaa, DARKNESS),
        Palette::interpolate(0x00aa00, 0x00aa00, DARKNESS),
        Palette::interpolate(0xaaaaaa, 0xffffff, DARKNESS),
        Palette::interpolate(0x000000, 0x555555, DARKNESS),
        Palette::interpolate(0x555555, 0xaaaaaa, DARKNESS),
        Palette::interpolate(0xaa0000, 0xaa0000, DARKNESS),
        Palette::interpolate(0xaa5500, 0xaa5500, DARKNESS),
        Palette::interpolate(0xffff55, 0xffff55, DARKNESS),
        Palette::interpolate(0x55ff55, 0x55ff55, DARKNESS),
        Palette::interpolate(0x00aa00, 0x00aa00, DARKNESS),
        Palette::interpolate(0x55ffff, 0x55ffff, DARKNESS),
        Palette::interpolate(0x00aaaa, 0x00aaaa, DARKNESS),
        Palette::interpolate(0x5555ff, 0x5555ff, DARKNESS),
        Palette::interpolate(0x0000af, 0x0000af, DARKNESS),
        Palette::interpolate(0xaa00aa, 0xaa00aa, DARKNESS),
        Palette::interpolate(0xff55ff, 0xff55ff, DARKNESS),
        Palette::interpolate(0xff5555, 0xff5a55, DARKNESS),
    ],
    // must be sorted!
    aliased: &[
        ("button-base", ColorIdx(Colors::Gray, 0)),
        ("container-arrow", ColorIdx(Colors::Gray, 0)),
        ("container-base", ColorIdx(Colors::Black, 0)),
        ("container-border", ColorIdx(Colors::Gray, 0)),
        ("dialog-arrow", ColorIdx(Colors::Black, 0)),
        ("dialog-base", ColorIdx(Colors::Gray, 0)),
        ("dialog-border", ColorIdx(Colors::Black, 0)),
        ("disabled", ColorIdx(Colors::Gray, 3)),
        ("focus", ColorIdx(Colors::Primary, 0)),
        ("footer", ColorIdx(Colors::None, 0)),
        ("footer-fg", ColorIdx(Colors::Blue, 0)),
        ("header", ColorIdx(Colors::None, 0)),
        ("header-fg", ColorIdx(Colors::Blue, 0)),
        ("hover", ColorIdx(Colors::Secondary, 0)),
        ("input", ColorIdx(Colors::Gray, 3)),
        ("invalid", ColorIdx(Colors::Red, 0)),
        ("key-binding", ColorIdx(Colors::Orange, 0)),
        ("label", ColorIdx(Colors::White, 0)),
        ("menu-base", ColorIdx(Colors::Black, 0)),
        ("month-header-fg", ColorIdx(Colors::Gray, 0)),
        ("popup-arrow", ColorIdx(Colors::Black, 0)),
        ("popup-base", ColorIdx(Colors::White, 0)),
        ("popup-border", ColorIdx(Colors::Black, 0)),
        ("select", ColorIdx(Colors::Secondary, 0)),
        ("shadows", ColorIdx(Colors::Black, 0)),
        ("status-base", ColorIdx(Colors::Black, 0)),
        ("text-focus", ColorIdx(Colors::Primary, 0)),
        ("text-select", ColorIdx(Colors::Secondary, 0)),
        ("title", ColorIdx(Colors::Red, 0)),
        ("title-fg", ColorIdx(Colors::TextLight, 0)),
        ("week-header-fg", ColorIdx(Colors::Gray, 0)),
    ],
};

