use crate::{ColorIdx, Colors, Palette};

/// Black&White
const DARKNESS: u8 = 63;

pub const BLACK_WHITE: Palette = Palette {
    name: "Black&White", 

    color: [
        Palette::interpolate2(0xffffff, 0xffffff, 0x0, 0x0),
        Palette::interpolate2(0x000000, 0x000000, 0x0, 0x0),
        Palette::interpolate(0xffffff, 0x000000, DARKNESS),
        Palette::interpolate(0xffffff, 0x000000, DARKNESS),
        Palette::interpolate(0xffffff, 0xffffff, DARKNESS),
        Palette::interpolate(0x000000, 0x000000, DARKNESS),
        Palette::interpolate(0xffffff, 0x000000, DARKNESS),
        Palette::interpolate(0xffffff, 0x7f7f7f, DARKNESS),
        Palette::interpolate(0xffffff, 0x7f7f7f, DARKNESS),
        Palette::interpolate(0xffffff, 0x7f7f7f, DARKNESS),
        Palette::interpolate(0xffffff, 0x7f7f7f, DARKNESS),
        Palette::interpolate(0xffffff, 0x7f7f7f, DARKNESS),
        Palette::interpolate(0xffffff, 0x7f7f7f, DARKNESS),
        Palette::interpolate(0xffffff, 0x7f7f7f, DARKNESS),
        Palette::interpolate(0xffffff, 0x7f7f7f, DARKNESS),
        Palette::interpolate(0xffffff, 0x7f7f7f, DARKNESS),
        Palette::interpolate(0xffffff, 0x7f7f7f, DARKNESS),
        Palette::interpolate(0xffffff, 0x7f7f7f, DARKNESS),
        Palette::interpolate(0xffffff, 0x7f7f7f, DARKNESS),
    ],
    // must be sorted!
    aliased: &[
        ("button-base.bg", ColorIdx(Colors::Gray, 1)),
        ("container-arrow.fg", ColorIdx(Colors::None, 0)),
        ("container-base.bg", ColorIdx(Colors::Black, 0)),
        ("container-border.fg", ColorIdx(Colors::None, 0)),
        ("dialog-arrow.fg", ColorIdx(Colors::None, 0)),
        ("dialog-base.bg", ColorIdx(Colors::Gray, 2)),
        ("dialog-border.fg", ColorIdx(Colors::None, 0)),
        ("disabled.bg", ColorIdx(Colors::Gray, 2)),
        ("document", ColorIdx(Colors::None, 0)),
        ("focus.bg", ColorIdx(Colors::Primary, 0)),
        ("footer.bg", ColorIdx(Colors::None, 0)),
        ("footer.fg", ColorIdx(Colors::Blue, 3)),
        ("header.bg", ColorIdx(Colors::None, 0)),
        ("header.fg", ColorIdx(Colors::Blue, 3)),
        ("heading-1", ColorIdx(Colors::None, 0)),
        ("heading-2", ColorIdx(Colors::None, 0)),
        ("hover.bg", ColorIdx(Colors::Gray, 0)),
        ("input.bg", ColorIdx(Colors::Gray, 1)),
        ("invalid.bg", ColorIdx(Colors::Red, 1)),
        ("key-binding.bg", ColorIdx(Colors::BlueGreen, 0)),
        ("label.fg", ColorIdx(Colors::White, 0)),
        ("menu-base.bg", ColorIdx(Colors::Black, 0)),
        ("month-header.fg", ColorIdx(Colors::None, 0)),
        ("popup-arrow.fg", ColorIdx(Colors::None, 0)),
        ("popup-base.bg", ColorIdx(Colors::White, 0)),
        ("popup-border.fg", ColorIdx(Colors::None, 0)),
        ("select.bg", ColorIdx(Colors::Secondary, 2)),
        ("shadow.bg", ColorIdx(Colors::Black, 0)),
        ("status-base.bg", ColorIdx(Colors::Black, 0)),
        ("sub-form", ColorIdx(Colors::None, 0)),
        ("text-focus.bg", ColorIdx(Colors::Primary, 0)),
        ("text-select.bg", ColorIdx(Colors::Secondary, 1)),
        ("title.bg", ColorIdx(Colors::Red, 3)),
        ("title.fg", ColorIdx(Colors::TextLight, 0)),
        ("week-header.fg", ColorIdx(Colors::Gray, 1)),
    ],
};

