use crate::{ColorIdx, Colors, Palette};

/// EverForest
const DARKNESS: u8 = 63;

pub const EVERFOREST: Palette = Palette {
    name: "EverForest",

    color: [
        Palette::interpolate2(0xd8d4cb, 0xf4f0e6, 0x0, 0x0),
        Palette::interpolate2(0x090a09, 0x2c2d2a, 0x0, 0x0),
        Palette::interpolate(0x69a59d, 0x69a59d, DARKNESS),
        Palette::interpolate(0x7393b3, 0x7393b3, DARKNESS),
        Palette::interpolate(0xd3c6aa, 0xc4ac7b, DARKNESS),
        Palette::interpolate(0x272f35, 0x30383d, DARKNESS),
        Palette::interpolate(0x4e565c, 0x656d73, DARKNESS),
        Palette::interpolate(0xe67e80, 0xfc8f93, DARKNESS),
        Palette::interpolate(0xe69875, 0xf4ab8b, DARKNESS),
        Palette::interpolate(0xdbbc7f, 0xddc187, DARKNESS),
        Palette::interpolate(0xa7c080, 0xb8ce94, DARKNESS),
        Palette::interpolate(0x83c092, 0x83c092, DARKNESS),
        Palette::interpolate(0x69a59d, 0x77ada6, DARKNESS),
        Palette::interpolate(0x95d1c9, 0xafdbd5, DARKNESS),
        Palette::interpolate(0x7393b3, 0x8fa7bf, DARKNESS),
        Palette::interpolate(0x78b4ac, 0x8dc4bd, DARKNESS),
        Palette::interpolate(0xd699b6, 0xe5b7cd, DARKNESS),
        Palette::interpolate(0xff75a0, 0xf5608e, DARKNESS),
        Palette::interpolate(0xce8196, 0xbf7082, DARKNESS),
    ],
    // must be sorted!
    aliased: &[
        ("button-base.bg", ColorIdx(Colors::Gray, 0)),
        ("container-arrow.fg", ColorIdx(Colors::None, 0)),
        ("container-base.bg", ColorIdx(Colors::Black, 2)),
        ("container-border.fg", ColorIdx(Colors::None, 0)),
        ("dialog-arrow.fg", ColorIdx(Colors::None, 0)),
        ("dialog-base.bg", ColorIdx(Colors::Gray, 3)),
        ("dialog-border.fg", ColorIdx(Colors::None, 0)),
        ("disabled.bg", ColorIdx(Colors::Gray, 3)),
        ("focus.bg", ColorIdx(Colors::Primary, 1)),
        ("footer.bg", ColorIdx(Colors::None, 0)),
        ("footer.fg", ColorIdx(Colors::DeepBlue, 0)),
        ("header.bg", ColorIdx(Colors::None, 0)),
        ("header.fg", ColorIdx(Colors::DeepBlue, 0)),
        ("hover.bg", ColorIdx(Colors::DeepBlue, 2)),
        ("input.bg", ColorIdx(Colors::White, 1)),
        ("invalid.bg", ColorIdx(Colors::Red, 1)),
        ("key-binding.bg", ColorIdx(Colors::Green, 0)),
        ("label.fg", ColorIdx(Colors::White, 0)),
        ("menu-base.bg", ColorIdx(Colors::Black, 1)),
        ("month-header.fg", ColorIdx(Colors::None, 0)),
        ("popup-arrow.fg", ColorIdx(Colors::None, 0)),
        ("popup-base.bg", ColorIdx(Colors::White, 3)),
        ("popup-border.fg", ColorIdx(Colors::None, 0)),
        ("select.bg", ColorIdx(Colors::Secondary, 1)),
        ("shadow.bg", ColorIdx(Colors::Black, 0)),
        ("status-base.bg", ColorIdx(Colors::Black, 1)),
        ("text-focus.bg", ColorIdx(Colors::Primary, 1)),
        ("text-select.bg", ColorIdx(Colors::Secondary, 1)),
        ("title.bg", ColorIdx(Colors::None, 0)),
        ("title.fg", ColorIdx(Colors::Magenta, 0)),
        ("week-header.fg", ColorIdx(Colors::Gray, 3)),
    ],
};
