use crate::{ColorIdx, Colors, Palette};

/// OxoCarbon
const DARKNESS: u8 = 63;

pub const OXOCARBON: Palette = Palette {
    name: "OxoCarbon",

    color: [
        Palette::interpolate2(0xf2f4f8, 0xf9fbff, 0x0, 0x0),
        Palette::interpolate2(0x0f0f0f, 0x202020, 0x0, 0x0),
        Palette::interpolate(0x78a9ff, 0x78a9ff, DARKNESS),
        Palette::interpolate(0xb5e8e0, 0xb5e8e0, DARKNESS),
        Palette::interpolate(0xdde1e6, 0xffffff, DARKNESS),
        Palette::interpolate(0x0f0f0f, 0x202020, DARKNESS),
        Palette::interpolate(0x464646, 0x5f5f5f, DARKNESS),
        Palette::interpolate(0xee5396, 0xee5396, DARKNESS),
        Palette::interpolate(0xf8bd96, 0xf8bd96, DARKNESS),
        Palette::interpolate(0xfae3b0, 0xfae3b0, DARKNESS),
        Palette::interpolate(0x08bdba, 0x08bdba, DARKNESS),
        Palette::interpolate(0x42be65, 0x42be65, DARKNESS),
        Palette::interpolate(0xb5e8e0, 0xb5e8e0, DARKNESS),
        Palette::interpolate(0x3ddbd9, 0x3ddbd9, DARKNESS),
        Palette::interpolate(0x33b1ff, 0x33b1ff, DARKNESS),
        Palette::interpolate(0x78a9ff, 0x78a9ff, DARKNESS),
        Palette::interpolate(0xbe95ff, 0xbe95ff, DARKNESS),
        Palette::interpolate(0xd0a9e5, 0xd0a9e5, DARKNESS),
        Palette::interpolate(0xff7eb6, 0xff77b4, DARKNESS),
    ],
    // must be sorted!
    aliased: &[
        ("button-base.bg", ColorIdx(Colors::Gray, 0)),
        ("container-arrow.fg", ColorIdx(Colors::None, 0)),
        ("container-base.bg", ColorIdx(Colors::Black, 2)),
        ("container-border.fg", ColorIdx(Colors::None, 0)),
        ("dialog-arrow.fg", ColorIdx(Colors::None, 0)),
        ("dialog-base.bg", ColorIdx(Colors::Gray, 2)),
        ("dialog-border.fg", ColorIdx(Colors::None, 0)),
        ("disabled.bg", ColorIdx(Colors::Gray, 3)),
        ("focus.bg", ColorIdx(Colors::Primary, 0)),
        ("footer.bg", ColorIdx(Colors::None, 0)),
        ("footer.fg", ColorIdx(Colors::DeepBlue, 0)),
        ("header.bg", ColorIdx(Colors::None, 0)),
        ("header.fg", ColorIdx(Colors::DeepBlue, 0)),
        ("hover.bg", ColorIdx(Colors::Secondary, 0)),
        ("input.bg", ColorIdx(Colors::Gray, 3)),
        ("invalid.bg", ColorIdx(Colors::Red, 1)),
        ("key-binding.bg", ColorIdx(Colors::BlueGreen, 0)),
        ("label.fg", ColorIdx(Colors::White, 0)),
        ("menu-base.bg", ColorIdx(Colors::Black, 1)),
        ("month-header.fg", ColorIdx(Colors::None, 0)),
        ("popup-arrow.fg", ColorIdx(Colors::None, 0)),
        ("popup-base.bg", ColorIdx(Colors::Gray, 0)),
        ("popup-border.fg", ColorIdx(Colors::None, 0)),
        ("select.bg", ColorIdx(Colors::Secondary, 0)),
        ("shadow.bg", ColorIdx(Colors::Black, 0)),
        ("status-base.bg", ColorIdx(Colors::Black, 1)),
        ("text-focus.bg", ColorIdx(Colors::Primary, 1)),
        ("text-select.bg", ColorIdx(Colors::Secondary, 1)),
        ("title.bg", ColorIdx(Colors::Red, 0)),
        ("title.fg", ColorIdx(Colors::TextLight, 0)),
        ("week-header.fg", ColorIdx(Colors::BlueGreen, 0)),
    ],
};
