use crate::{ColorIdx, Colors, Palette};

/// Reds
const DARKNESS: u8 = 63;

pub const REDS: Palette = Palette {
    name: "Reds", 

    color: [
        Palette::interpolate2(0xcfafaf, 0xe2cfcf, 0x0, 0x0),
        Palette::interpolate2(0x160d0d, 0x3a2323, 0x0, 0x0),
        Palette::interpolate(0xa50000, 0xa55454, DARKNESS),
        Palette::interpolate(0xa52300, 0xa56654, DARKNESS),
        Palette::interpolate(0xcfafaf, 0xe2cfcf, DARKNESS),
        Palette::interpolate(0x160d0d, 0x3a2323, DARKNESS),
        Palette::interpolate(0x6f4343, 0xbd8f8f, DARKNESS),
        Palette::interpolate(0xff7f7f, 0xffcccc, DARKNESS),
        Palette::interpolate(0xff7f7f, 0xffcccc, DARKNESS),
        Palette::interpolate(0xff7f7f, 0xffcccc, DARKNESS),
        Palette::interpolate(0xff7f7f, 0xffcccc, DARKNESS),
        Palette::interpolate(0xff7f7f, 0xffcccc, DARKNESS),
        Palette::interpolate(0xff7f7f, 0xffcccc, DARKNESS),
        Palette::interpolate(0xff7f7f, 0xffcccc, DARKNESS),
        Palette::interpolate(0xff7f7f, 0xffcccc, DARKNESS),
        Palette::interpolate(0xff7f7f, 0xffcccc, DARKNESS),
        Palette::interpolate(0xff7f7f, 0xffcccc, DARKNESS),
        Palette::interpolate(0xff7f7f, 0xffcccc, DARKNESS),
        Palette::interpolate(0xff7f7f, 0xffcccc, DARKNESS),
    ],
    // must be sorted!
    aliased: &[
        ("button-base", ColorIdx(Colors::Gray, 0)),
        ("container-arrow", ColorIdx(Colors::Gray, 1)),
        ("container-base", ColorIdx(Colors::Black, 1)),
        ("container-border", ColorIdx(Colors::Gray, 1)),
        ("dialog-arrow", ColorIdx(Colors::Black, 3)),
        ("dialog-base", ColorIdx(Colors::Gray, 2)),
        ("dialog-border", ColorIdx(Colors::Black, 3)),
        ("disabled", ColorIdx(Colors::Gray, 3)),
        ("focus", ColorIdx(Colors::Primary, 1)),
        ("footer", ColorIdx(Colors::Black, 1)),
        ("footer-fg", ColorIdx(Colors::Blue, 2)),
        ("header", ColorIdx(Colors::Black, 1)),
        ("header-fg", ColorIdx(Colors::Blue, 2)),
        ("hover", ColorIdx(Colors::Secondary, 1)),
        ("input", ColorIdx(Colors::Gray, 2)),
        ("invalid", ColorIdx(Colors::Red, 1)),
        ("key-binding", ColorIdx(Colors::BlueGreen, 0)),
        ("label", ColorIdx(Colors::White, 0)),
        ("menu-base", ColorIdx(Colors::Black, 0)),
        ("month-header-fg", ColorIdx(Colors::None, 0)),
        ("popup-arrow", ColorIdx(Colors::Gray, 3)),
        ("popup-base", ColorIdx(Colors::Gray, 1)),
        ("popup-border", ColorIdx(Colors::Gray, 3)),
        ("select", ColorIdx(Colors::Secondary, 3)),
        ("shadows", ColorIdx(Colors::None, 0)),
        ("status-base", ColorIdx(Colors::Black, 0)),
        ("text-focus", ColorIdx(Colors::Primary, 1)),
        ("text-select", ColorIdx(Colors::Secondary, 1)),
        ("title", ColorIdx(Colors::Red, 0)),
        ("title-fg", ColorIdx(Colors::TextLight, 0)),
        ("week-header-fg", ColorIdx(Colors::None, 0)),
    ],
};

