use crate::{ColorIdx, Colors, Palette};

/// Reds
const DARKNESS: u8 = 63;

pub const REDS: Palette = Palette {
    name: "Reds",

    color: [
        Palette::interpolate2(0xcfafaf, 0xe2cfcf, 0x0, 0x0),
        Palette::interpolate2(0x160d0d, 0x3a2323, 0x0, 0x0),
        Palette::interpolate(0xa50000, 0xa55454, DARKNESS),
        Palette::interpolate(0xa52300, 0xa56654, DARKNESS),
        Palette::interpolate(0xcfafaf, 0xe2cfcf, DARKNESS),
        Palette::interpolate(0x160d0d, 0x3a2323, DARKNESS),
        Palette::interpolate(0x6f4343, 0xbd8f8f, DARKNESS),
        Palette::interpolate(0xff7f7f, 0xffcccc, DARKNESS),
        Palette::interpolate(0xff7f7f, 0xffcccc, DARKNESS),
        Palette::interpolate(0xff7f7f, 0xffcccc, DARKNESS),
        Palette::interpolate(0xff7f7f, 0xffcccc, DARKNESS),
        Palette::interpolate(0xff7f7f, 0xffcccc, DARKNESS),
        Palette::interpolate(0xff7f7f, 0xffcccc, DARKNESS),
        Palette::interpolate(0xff7f7f, 0xffcccc, DARKNESS),
        Palette::interpolate(0xff7f7f, 0xffcccc, DARKNESS),
        Palette::interpolate(0xff7f7f, 0xffcccc, DARKNESS),
        Palette::interpolate(0xff7f7f, 0xffcccc, DARKNESS),
        Palette::interpolate(0xff7f7f, 0xffcccc, DARKNESS),
        Palette::interpolate(0xff7f7f, 0xffcccc, DARKNESS),
    ],
    // must be sorted!
    aliased: &[
        ("button-base.bg", ColorIdx(Colors::Gray, 0)),
        ("container-arrow.fg", ColorIdx(Colors::None, 0)),
        ("container-base.bg", ColorIdx(Colors::Black, 1)),
        ("container-border.fg", ColorIdx(Colors::None, 0)),
        ("dialog-arrow.fg", ColorIdx(Colors::None, 0)),
        ("dialog-base.bg", ColorIdx(Colors::Gray, 2)),
        ("dialog-border.fg", ColorIdx(Colors::None, 0)),
        ("disabled.bg", ColorIdx(Colors::Gray, 3)),
        ("focus.bg", ColorIdx(Colors::Primary, 1)),
        ("footer.bg", ColorIdx(Colors::Black, 1)),
        ("footer.fg", ColorIdx(Colors::Blue, 2)),
        ("header.bg", ColorIdx(Colors::Black, 1)),
        ("header.fg", ColorIdx(Colors::Blue, 2)),
        ("hover.bg", ColorIdx(Colors::Secondary, 1)),
        ("input.bg", ColorIdx(Colors::Gray, 2)),
        ("invalid.bg", ColorIdx(Colors::Red, 1)),
        ("key-binding.bg", ColorIdx(Colors::BlueGreen, 0)),
        ("label.fg", ColorIdx(Colors::White, 0)),
        ("menu-base.bg", ColorIdx(Colors::Black, 0)),
        ("month-header.fg", ColorIdx(Colors::None, 0)),
        ("popup-arrow.fg", ColorIdx(Colors::None, 0)),
        ("popup-base.bg", ColorIdx(Colors::Gray, 1)),
        ("popup-border.fg", ColorIdx(Colors::None, 0)),
        ("select.bg", ColorIdx(Colors::Secondary, 3)),
        ("shadow.bg", ColorIdx(Colors::None, 0)),
        ("status-base.bg", ColorIdx(Colors::Black, 0)),
        ("text-focus.bg", ColorIdx(Colors::Primary, 1)),
        ("text-select.bg", ColorIdx(Colors::Secondary, 1)),
        ("title.bg", ColorIdx(Colors::Red, 0)),
        ("title.fg", ColorIdx(Colors::TextLight, 0)),
        ("week-header.fg", ColorIdx(Colors::None, 0)),
    ],
};
