use crate::{ColorIdx, Colors, Palette};

/// Rust
/// Rusty theme.
const DARKNESS: u8 = 63;

pub const RUST: Palette = Palette {
    name: "Rust",

    color: [
        Palette::interpolate2(0xd1ccc8, 0xefe6e6, 0x0, 0x0),
        Palette::interpolate2(0x161514, 0x0f0e0d, 0x0, 0x0),
        Palette::interpolate(0x75311a, 0xd25a32, DARKNESS),
        Palette::interpolate(0x77551d, 0xcd9537, DARKNESS),
        Palette::interpolate(0xc4bfbb, 0xede3e3, DARKNESS),
        Palette::interpolate(0x101011, 0x464251, DARKNESS),
        Palette::interpolate(0x726e6b, 0xa39d99, DARKNESS),
        Palette::interpolate(0x75311a, 0xd25a32, DARKNESS),
        Palette::interpolate(0x75431a, 0xd27a32, DARKNESS),
        Palette::interpolate(0x77551d, 0xcd9537, DARKNESS),
        Palette::interpolate(0x44664d, 0x699b76, DARKNESS),
        Palette::interpolate(0x44664d, 0x699b76, DARKNESS),
        Palette::interpolate(0x1a7574, 0x32d2d1, DARKNESS),
        Palette::interpolate(0x1a7574, 0x32d2d1, DARKNESS),
        Palette::interpolate(0x005d94, 0x38b6ff, DARKNESS),
        Palette::interpolate(0x005d94, 0x38b6ff, DARKNESS),
        Palette::interpolate(0x722234, 0xc63f5d, DARKNESS),
        Palette::interpolate(0x7b1964, 0xc62fa3, DARKNESS),
        Palette::interpolate(0x7b1964, 0xd332ad, DARKNESS),
    ],
    // must be sorted!
    aliased: &[
        ("button-base", ColorIdx(Colors::Gray, 0)),
        ("container-arrow", ColorIdx(Colors::Gray, 1)),
        ("container-base", ColorIdx(Colors::Black, 1)),
        ("container-border", ColorIdx(Colors::Gray, 1)),
        ("dialog-arrow", ColorIdx(Colors::Black, 3)),
        ("dialog-base", ColorIdx(Colors::Gray, 2)),
        ("dialog-border", ColorIdx(Colors::Black, 3)),
        ("disabled", ColorIdx(Colors::Gray, 3)),
        ("focus", ColorIdx(Colors::Primary, 1)),
        ("footer", ColorIdx(Colors::None, 0)),
        ("footer-fg", ColorIdx(Colors::Blue, 0)),
        ("header", ColorIdx(Colors::None, 0)),
        ("header-fg", ColorIdx(Colors::Blue, 0)),
        ("hover", ColorIdx(Colors::Blue, 0)),
        ("input", ColorIdx(Colors::Gray, 3)),
        ("invalid", ColorIdx(Colors::Purple, 1)),
        ("key-binding", ColorIdx(Colors::BlueGreen, 0)),
        ("label", ColorIdx(Colors::White, 2)),
        ("menu-base", ColorIdx(Colors::Black, 0)),
        ("month-header-fg", ColorIdx(Colors::None, 0)),
        ("popup-arrow", ColorIdx(Colors::Gray, 3)),
        ("popup-base", ColorIdx(Colors::White, 0)),
        ("popup-border", ColorIdx(Colors::Gray, 3)),
        ("select", ColorIdx(Colors::Secondary, 1)),
        ("shadows", ColorIdx(Colors::TextDark, 0)),
        ("status-base", ColorIdx(Colors::Black, 0)),
        ("text-focus", ColorIdx(Colors::Primary, 1)),
        ("text-select", ColorIdx(Colors::Secondary, 1)),
        ("title", ColorIdx(Colors::Primary, 1)),
        ("title-fg", ColorIdx(Colors::TextLight, 0)),
        ("week-header-fg", ColorIdx(Colors::Gray, 1)),
    ],
};
