use crate::{ColorIdx, Colors, Palette};

/// Solarized
/// credit https://github.com/altercation/solarized/tree/master/vim-colors-solarized
const DARKNESS: u8 = 63;

pub const SOLARIZED: Palette = Palette {
    name: "Solarized",

    color: [
        Palette::interpolate2(0xeee8d5, 0xfdf6e3, 0x0, 0x0),
        Palette::interpolate2(0x002b36, 0x073642, 0x0, 0x0),
        Palette::interpolate(0xcb4b16, 0xcb4b16, DARKNESS),
        Palette::interpolate(0x586e75, 0x839496, DARKNESS),
        Palette::interpolate(0xeee8d5, 0xfdf6e3, DARKNESS),
        Palette::interpolate(0x002b36, 0x073642, DARKNESS),
        Palette::interpolate(0x586e75, 0x839496, DARKNESS),
        Palette::interpolate(0xdc322f, 0xdc322f, DARKNESS),
        Palette::interpolate(0xcb4b16, 0xcb4b16, DARKNESS),
        Palette::interpolate(0xb58900, 0xb58900, DARKNESS),
        Palette::interpolate(0x859900, 0x859900, DARKNESS),
        Palette::interpolate(0x859900, 0x859900, DARKNESS),
        Palette::interpolate(0x2aa198, 0x2aa198, DARKNESS),
        Palette::interpolate(0x2aa198, 0x2aa198, DARKNESS),
        Palette::interpolate(0x268bd2, 0x268bd2, DARKNESS),
        Palette::interpolate(0x268bd2, 0x268bd2, DARKNESS),
        Palette::interpolate(0x6c71c4, 0x6c71c4, DARKNESS),
        Palette::interpolate(0xd33682, 0xd33682, DARKNESS),
        Palette::interpolate(0xd33682, 0xd33c82, DARKNESS),
    ],
    // must be sorted!
    aliased: &[
        ("button-base", ColorIdx(Colors::Secondary, 3)),
        ("container-arrow", ColorIdx(Colors::Gray, 3)),
        ("container-base", ColorIdx(Colors::TextDark, 0)),
        ("container-border", ColorIdx(Colors::Gray, 3)),
        ("dialog-arrow", ColorIdx(Colors::TextDark, 0)),
        ("dialog-base", ColorIdx(Colors::Gray, 1)),
        ("dialog-border", ColorIdx(Colors::TextDark, 0)),
        ("disabled", ColorIdx(Colors::Gray, 0)),
        ("focus", ColorIdx(Colors::Primary, 1)),
        ("footer", ColorIdx(Colors::None, 0)),
        ("footer-fg", ColorIdx(Colors::Blue, 0)),
        ("header", ColorIdx(Colors::None, 0)),
        ("header-fg", ColorIdx(Colors::Blue, 0)),
        ("hover", ColorIdx(Colors::Blue, 0)),
        ("input", ColorIdx(Colors::Gray, 3)),
        ("invalid", ColorIdx(Colors::Red, 0)),
        ("key-binding", ColorIdx(Colors::Black, 0)),
        ("label", ColorIdx(Colors::TextLight, 0)),
        ("menu-base", ColorIdx(Colors::Black, 0)),
        ("month-header-fg", ColorIdx(Colors::None, 0)),
        ("popup-arrow", ColorIdx(Colors::TextDark, 0)),
        ("popup-base", ColorIdx(Colors::Gray, 1)),
        ("popup-border", ColorIdx(Colors::TextDark, 0)),
        ("select", ColorIdx(Colors::Secondary, 0)),
        ("shadows", ColorIdx(Colors::Black, 0)),
        ("status-base", ColorIdx(Colors::Black, 0)),
        ("text-focus", ColorIdx(Colors::Primary, 1)),
        ("text-select", ColorIdx(Colors::Secondary, 0)),
        ("title", ColorIdx(Colors::None, 0)),
        ("title-fg", ColorIdx(Colors::Blue, 0)),
        ("week-header-fg", ColorIdx(Colors::Gray, 3)),
    ],
};
