use crate::{ColorIdx, Colors, Palette};

/// Solarized
/// credit https://github.com/altercation/solarized/tree/master/vim-colors-solarized
const DARKNESS: u8 = 63;

pub const SOLARIZED: Palette = Palette {
    name: "Solarized", 

    color: [
        Palette::interpolate2(0xeee8d5, 0xfdf6e3, 0x0, 0x0),
        Palette::interpolate2(0x002b36, 0x073642, 0x0, 0x0),
        Palette::interpolate(0xcb4b16, 0xcb4b16, DARKNESS),
        Palette::interpolate(0x586e75, 0x839496, DARKNESS),
        Palette::interpolate(0xeee8d5, 0xfdf6e3, DARKNESS),
        Palette::interpolate(0x002b36, 0x073642, DARKNESS),
        Palette::interpolate(0x586e75, 0x839496, DARKNESS),
        Palette::interpolate(0xdc322f, 0xdc322f, DARKNESS),
        Palette::interpolate(0xcb4b16, 0xcb4b16, DARKNESS),
        Palette::interpolate(0xb58900, 0xb58900, DARKNESS),
        Palette::interpolate(0x859900, 0x859900, DARKNESS),
        Palette::interpolate(0x859900, 0x859900, DARKNESS),
        Palette::interpolate(0x2aa198, 0x2aa198, DARKNESS),
        Palette::interpolate(0x2aa198, 0x2aa198, DARKNESS),
        Palette::interpolate(0x268bd2, 0x268bd2, DARKNESS),
        Palette::interpolate(0x268bd2, 0x268bd2, DARKNESS),
        Palette::interpolate(0x6c71c4, 0x6c71c4, DARKNESS),
        Palette::interpolate(0xd33682, 0xd33682, DARKNESS),
        Palette::interpolate(0xd33682, 0xd33c82, DARKNESS),
    ],
    // must be sorted!
    aliased: &[
        ("button-base.bg", ColorIdx(Colors::Secondary, 3)),
        ("container-arrow.fg", ColorIdx(Colors::None, 0)),
        ("container-base.bg", ColorIdx(Colors::TextDark, 0)),
        ("container-border.fg", ColorIdx(Colors::None, 0)),
        ("dialog-arrow.fg", ColorIdx(Colors::None, 0)),
        ("dialog-base.bg", ColorIdx(Colors::Gray, 1)),
        ("dialog-border.fg", ColorIdx(Colors::None, 0)),
        ("disabled.bg", ColorIdx(Colors::Gray, 0)),
        ("document", ColorIdx(Colors::None, 0)),
        ("focus.bg", ColorIdx(Colors::Primary, 1)),
        ("footer.bg", ColorIdx(Colors::None, 0)),
        ("footer.fg", ColorIdx(Colors::Blue, 0)),
        ("header.bg", ColorIdx(Colors::None, 0)),
        ("header.fg", ColorIdx(Colors::Blue, 0)),
        ("heading-1", ColorIdx(Colors::None, 0)),
        ("heading-2", ColorIdx(Colors::None, 0)),
        ("hover.bg", ColorIdx(Colors::Blue, 0)),
        ("input.bg", ColorIdx(Colors::Gray, 3)),
        ("invalid.bg", ColorIdx(Colors::Red, 0)),
        ("key-binding.bg", ColorIdx(Colors::Black, 0)),
        ("label.fg", ColorIdx(Colors::TextLight, 0)),
        ("menu-base.bg", ColorIdx(Colors::Black, 0)),
        ("month-header.fg", ColorIdx(Colors::None, 0)),
        ("popup-arrow.fg", ColorIdx(Colors::None, 0)),
        ("popup-base.bg", ColorIdx(Colors::Gray, 1)),
        ("popup-border.fg", ColorIdx(Colors::None, 0)),
        ("select.bg", ColorIdx(Colors::Secondary, 0)),
        ("shadow.bg", ColorIdx(Colors::Black, 0)),
        ("status-base.bg", ColorIdx(Colors::Black, 0)),
        ("sub-form", ColorIdx(Colors::None, 0)),
        ("text-focus.bg", ColorIdx(Colors::Primary, 1)),
        ("text-select.bg", ColorIdx(Colors::Secondary, 0)),
        ("title.bg", ColorIdx(Colors::None, 0)),
        ("title.fg", ColorIdx(Colors::Blue, 0)),
        ("week-header.fg", ColorIdx(Colors::Gray, 3)),
    ],
};

