use crate::{ColorIdx, Colors, Palette};

/// VSCode
const DARKNESS: u8 = 63;

pub const VSCODE: Palette = Palette {
    name: "VSCode", 

    color: [
        Palette::interpolate2(0xd4d4d4, 0xffffff, 0x0, 0x0),
        Palette::interpolate2(0x1a1a1a, 0x3a3a3a, 0x0, 0x0),
        Palette::interpolate(0xd4d4d4, 0xffffff, DARKNESS),
        Palette::interpolate(0x444444, 0x878787, DARKNESS),
        Palette::interpolate(0xd4d4d4, 0xffffff, DARKNESS),
        Palette::interpolate(0x1a1a1a, 0x3a3a3a, DARKNESS),
        Palette::interpolate(0x444444, 0x878787, DARKNESS),
        Palette::interpolate(0xd16969, 0xd16969, DARKNESS),
        Palette::interpolate(0xd57e62, 0xd3967d, DARKNESS),
        Palette::interpolate(0xd7ba7d, 0xd7ba7d, DARKNESS),
        Palette::interpolate(0x9cda80, 0x9cda80, DARKNESS),
        Palette::interpolate(0x80daba, 0x80daba, DARKNESS),
        Palette::interpolate(0xb5cea8, 0xb5cea8, DARKNESS),
        Palette::interpolate(0x9cdcfe, 0x9cdcfe, DARKNESS),
        Palette::interpolate(0x89beec, 0x89beec, DARKNESS),
        Palette::interpolate(0x85bae6, 0x85bae6, DARKNESS),
        Palette::interpolate(0xbd88ed, 0xbd88ed, DARKNESS),
        Palette::interpolate(0xbb7cb6, 0xbb7cb6, DARKNESS),
        Palette::interpolate(0xe98691, 0xe98691, DARKNESS),
    ],
    // must be sorted!
    aliased: &[
        ("button-base.bg", ColorIdx(Colors::Gray, 0)),
        ("container-arrow.fg", ColorIdx(Colors::None, 0)),
        ("container-base.bg", ColorIdx(Colors::Black, 0)),
        ("container-border.fg", ColorIdx(Colors::None, 0)),
        ("dialog-arrow.fg", ColorIdx(Colors::None, 0)),
        ("dialog-base.bg", ColorIdx(Colors::Gray, 2)),
        ("dialog-border.fg", ColorIdx(Colors::None, 0)),
        ("disabled.bg", ColorIdx(Colors::Gray, 3)),
        ("document", ColorIdx(Colors::None, 0)),
        ("focus.bg", ColorIdx(Colors::Primary, 1)),
        ("footer.bg", ColorIdx(Colors::None, 0)),
        ("footer.fg", ColorIdx(Colors::Cyan, 0)),
        ("header.bg", ColorIdx(Colors::None, 0)),
        ("header.fg", ColorIdx(Colors::Cyan, 0)),
        ("heading-1", ColorIdx(Colors::None, 0)),
        ("heading-2", ColorIdx(Colors::None, 0)),
        ("hover.bg", ColorIdx(Colors::Black, 0)),
        ("input.bg", ColorIdx(Colors::Gray, 3)),
        ("invalid.bg", ColorIdx(Colors::Red, 1)),
        ("key-binding.bg", ColorIdx(Colors::BlueGreen, 0)),
        ("label.fg", ColorIdx(Colors::White, 0)),
        ("menu-base.bg", ColorIdx(Colors::Black, 0)),
        ("month-header.fg", ColorIdx(Colors::None, 0)),
        ("popup-arrow.fg", ColorIdx(Colors::None, 0)),
        ("popup-base.bg", ColorIdx(Colors::White, 0)),
        ("popup-border.fg", ColorIdx(Colors::None, 0)),
        ("select.bg", ColorIdx(Colors::Secondary, 1)),
        ("shadow.bg", ColorIdx(Colors::Black, 0)),
        ("status-base.bg", ColorIdx(Colors::Black, 0)),
        ("sub-form", ColorIdx(Colors::None, 0)),
        ("text-focus.bg", ColorIdx(Colors::Primary, 1)),
        ("text-select.bg", ColorIdx(Colors::Secondary, 1)),
        ("title.bg", ColorIdx(Colors::Red, 0)),
        ("title.fg", ColorIdx(Colors::TextLight, 0)),
        ("week-header.fg", ColorIdx(Colors::Gray, 3)),
    ],
};

