use crate::{ColorIdx, Colors, Palette};

/// VSCode
const DARKNESS: u8 = 63;

pub const VSCODE: Palette = Palette {
    name: "VSCode", 

    color: [
        Palette::interpolate2(0xd4d4d4, 0xffffff, 0x0, 0x0),
        Palette::interpolate2(0x1a1a1a, 0x3a3a3a, 0x0, 0x0),
        Palette::interpolate(0xd4d4d4, 0xffffff, DARKNESS),
        Palette::interpolate(0x444444, 0x878787, DARKNESS),
        Palette::interpolate(0xd4d4d4, 0xffffff, DARKNESS),
        Palette::interpolate(0x1a1a1a, 0x3a3a3a, DARKNESS),
        Palette::interpolate(0x444444, 0x878787, DARKNESS),
        Palette::interpolate(0xd16969, 0xd16969, DARKNESS),
        Palette::interpolate(0xd57e62, 0xd3967d, DARKNESS),
        Palette::interpolate(0xd7ba7d, 0xd7ba7d, DARKNESS),
        Palette::interpolate(0x9cda80, 0x9cda80, DARKNESS),
        Palette::interpolate(0x80daba, 0x80daba, DARKNESS),
        Palette::interpolate(0xb5cea8, 0xb5cea8, DARKNESS),
        Palette::interpolate(0x9cdcfe, 0x9cdcfe, DARKNESS),
        Palette::interpolate(0x89beec, 0x89beec, DARKNESS),
        Palette::interpolate(0x85bae6, 0x85bae6, DARKNESS),
        Palette::interpolate(0xbd88ed, 0xbd88ed, DARKNESS),
        Palette::interpolate(0xbb7cb6, 0xbb7cb6, DARKNESS),
        Palette::interpolate(0xe98691, 0xe98691, DARKNESS),
    ],
    // must be sorted!
    aliased: &[
        ("button-base", ColorIdx(Colors::Gray, 0)),
        ("container-arrow", ColorIdx(Colors::Gray, 1)),
        ("container-base", ColorIdx(Colors::Black, 0)),
        ("container-border", ColorIdx(Colors::Gray, 1)),
        ("dialog-arrow", ColorIdx(Colors::Black, 3)),
        ("dialog-base", ColorIdx(Colors::Gray, 2)),
        ("dialog-border", ColorIdx(Colors::Black, 3)),
        ("disabled", ColorIdx(Colors::Gray, 3)),
        ("focus", ColorIdx(Colors::Primary, 1)),
        ("footer", ColorIdx(Colors::None, 0)),
        ("footer-fg", ColorIdx(Colors::Cyan, 0)),
        ("header", ColorIdx(Colors::None, 0)),
        ("header-fg", ColorIdx(Colors::Cyan, 0)),
        ("hover", ColorIdx(Colors::Black, 0)),
        ("input", ColorIdx(Colors::Gray, 3)),
        ("invalid", ColorIdx(Colors::Red, 1)),
        ("key-binding", ColorIdx(Colors::BlueGreen, 0)),
        ("label", ColorIdx(Colors::White, 0)),
        ("menu-base", ColorIdx(Colors::Black, 0)),
        ("month-header-fg", ColorIdx(Colors::None, 0)),
        ("popup-arrow", ColorIdx(Colors::Gray, 3)),
        ("popup-base", ColorIdx(Colors::White, 0)),
        ("popup-border", ColorIdx(Colors::Gray, 3)),
        ("select", ColorIdx(Colors::Secondary, 1)),
        ("shadows", ColorIdx(Colors::Black, 0)),
        ("status-base", ColorIdx(Colors::Black, 0)),
        ("text-focus", ColorIdx(Colors::Primary, 1)),
        ("text-select", ColorIdx(Colors::Secondary, 1)),
        ("title", ColorIdx(Colors::Red, 0)),
        ("title-fg", ColorIdx(Colors::TextLight, 0)),
        ("week-header-fg", ColorIdx(Colors::Gray, 3)),
    ],
};

