use std::borrow::Cow;
use crate::palette::{Colors, Palette, define_alias};

const DARKNESS: u8 = 63;

/// Gatekeeper
pub const GATEKEEPER_SHELL: Palette = Palette {
    theme_name: Cow::Borrowed("Gatekeeper Shell"), 
    theme: Cow::Borrowed("Shell"), 
    name: Cow::Borrowed("Gatekeeper"), 
    doc: Cow::Borrowed(""), 
    generator: Cow::Borrowed("light-dark:63"), 

    color: [
        Palette::interpolate2(0xcccdd1, 0xf9faff, 0x0, 0x0),
        Palette::interpolate2(0x0a0a0a, 0x000000, 0x0, 0x0),
        Palette::interpolate(0x0b925c, 0x0fc47c, DARKNESS),
        Palette::interpolate(0x636363, 0x939393, DARKNESS),
        Palette::interpolate(0xcccdd1, 0xeff0f4, DARKNESS),
        Palette::interpolate(0x0a0a0a, 0x181818, DARKNESS),
        Palette::interpolate(0x363636, 0x4d4d4d, DARKNESS),
        Palette::interpolate(0xff1a67, 0xff1a67, DARKNESS),
        Palette::interpolate(0xffa300, 0xffa300, DARKNESS),
        Palette::interpolate(0xfff024, 0xfff024, DARKNESS),
        Palette::interpolate(0x10f766, 0x10f766, DARKNESS),
        Palette::interpolate(0x00e756, 0x00e756, DARKNESS),
        Palette::interpolate(0x0c965f, 0x0b925c, DARKNESS),
        Palette::interpolate(0x29adff, 0x29adff, DARKNESS),
        Palette::interpolate(0x29adff, 0x29adff, DARKNESS),
        Palette::interpolate(0x5c6ab2, 0x5c6ab2, DARKNESS),
        Palette::interpolate(0x998cb2, 0x998cb2, DARKNESS),
        Palette::interpolate(0xff77a8, 0xff77a8, DARKNESS),
        Palette::interpolate(0xff86b7, 0xff86b7, DARKNESS),
    ],
    // must be sorted!
    aliased: Cow::Borrowed(&[
        define_alias("button-base.bg", Colors::Gray, 2),
        define_alias("container-arrow.fg", Colors::Gray, 3),
        define_alias("container-base.bg", Colors::None, 0),
        define_alias("container-border.fg", Colors::Gray, 3),
        define_alias("dialog-arrow.fg", Colors::White, 0),
        define_alias("dialog-base.bg", Colors::None, 0),
        define_alias("dialog-border.fg", Colors::White, 0),
        define_alias("disabled.bg", Colors::Gray, 2),
        define_alias("document-arrow.fg", Colors::Gray, 3),
        define_alias("document-base.bg", Colors::None, 0),
        define_alias("document-border.fg", Colors::Gray, 3),
        define_alias("focus.bg", Colors::Primary, 2),
        define_alias("footer.bg", Colors::BlueGreen, 0),
        define_alias("footer.fg", Colors::TextLight, 2),
        define_alias("header.bg", Colors::BlueGreen, 0),
        define_alias("header.fg", Colors::TextLight, 2),
        define_alias("hover.bg", Colors::Primary, 3),
        define_alias("input-focus.bg", Colors::Primary, 2),
        define_alias("input-select.bg", Colors::Gray, 3),
        define_alias("input.bg", Colors::Gray, 2),
        define_alias("invalid.bg", Colors::Red, 1),
        define_alias("key-binding.bg", Colors::DeepBlue, 0),
        define_alias("label.fg", Colors::TextLight, 0),
        define_alias("menu-base.bg", Colors::Black, 3),
        define_alias("month-header.fg", Colors::TextLight, 0),
        define_alias("popup-arrow.fg", Colors::Gray, 3),
        define_alias("popup-base.bg", Colors::Primary, 1),
        define_alias("popup-border.fg", Colors::Gray, 3),
        define_alias("select.bg", Colors::Gray, 3),
        define_alias("shadow.bg", Colors::White, 0),
        define_alias("status-base.bg", Colors::Black, 3),
        define_alias("title.bg", Colors::BlueGreen, 0),
        define_alias("title.fg", Colors::Green, 4),
        define_alias("week-header.fg", Colors::TextLight, 3),
    ]),
};

