use crate::palette::{Colors, Palette, define_alias};
use std::borrow::Cow;

const DARKNESS: u8 = 64;

/// Material.
/// Credits to original theme https://github.com/marko-cerovac/material.nvim
pub const MATERIAL_SHELL: Palette = Palette {
    theme_name: Cow::Borrowed("Material Shell"),
    theme: Cow::Borrowed("Shell"),
    name: Cow::Borrowed("Material"),
    doc: Cow::Borrowed("Credits to original theme https://github.com/marko-cerovac/material.nvim"),
    generator: Cow::Borrowed("light-dark:64"),

    color: [
        Palette::interpolate2(0xeeffff, 0xeeffff, 0x0, 0x0),
        Palette::interpolate2(0x191919, 0x191919, 0x0, 0x0),
        Palette::interpolate(0xcca055, 0xffcb6b, DARKNESS),
        Palette::interpolate(0x96b26c, 0xc3e88d, DARKNESS),
        Palette::interpolate(0xeeffff, 0xeeffff, DARKNESS),
        Palette::interpolate(0x191919, 0x292929, DARKNESS),
        Palette::interpolate(0x4a4a4a, 0x6b6b6b, DARKNESS),
        Palette::interpolate(0xf07178, 0xf07178, DARKNESS),
        Palette::interpolate(0xf78c6c, 0xf78c6c, DARKNESS),
        Palette::interpolate(0xffcb6b, 0xffcb6b, DARKNESS),
        Palette::interpolate(0xc3e88d, 0xc3e88d, DARKNESS),
        Palette::interpolate(0xc3e88d, 0xc3e88d, DARKNESS),
        Palette::interpolate(0xabcf76, 0xabcf76, DARKNESS),
        Palette::interpolate(0x89ddff, 0x89ddff, DARKNESS),
        Palette::interpolate(0x82aaff, 0x82aaff, DARKNESS),
        Palette::interpolate(0x6e98eb, 0x6e98eb, DARKNESS),
        Palette::interpolate(0xb480d6, 0xb480d6, DARKNESS),
        Palette::interpolate(0xda70ca, 0xda70ca, DARKNESS),
        Palette::interpolate(0xffadff, 0xffadff, DARKNESS),
    ],
    // must be sorted!
    aliased: Cow::Borrowed(&[
        define_alias("button-base.bg", Colors::Gray, 0),
        define_alias("container-arrow.fg", Colors::Gray, 1),
        define_alias("container-base.bg", Colors::None, 0),
        define_alias("container-border.fg", Colors::Gray, 1),
        define_alias("dialog-arrow.fg", Colors::White, 0),
        define_alias("dialog-base.bg", Colors::Magenta, 7),
        define_alias("dialog-border.fg", Colors::White, 0),
        define_alias("disabled.bg", Colors::Gray, 3),
        define_alias("document-arrow.fg", Colors::Gray, 1),
        define_alias("document-base.bg", Colors::Black, 0),
        define_alias("document-border.fg", Colors::Gray, 1),
        define_alias("focus.bg", Colors::Primary, 1),
        define_alias("footer.bg", Colors::None, 0),
        define_alias("footer.fg", Colors::Blue, 0),
        define_alias("header.bg", Colors::None, 0),
        define_alias("header.fg", Colors::Blue, 0),
        define_alias("hover.bg", Colors::Gray, 2),
        define_alias("input-focus.bg", Colors::Primary, 1),
        define_alias("input-select.bg", Colors::Secondary, 1),
        define_alias("input.bg", Colors::Gray, 2),
        define_alias("invalid.bg", Colors::Red, 1),
        define_alias("key-binding.bg", Colors::Secondary, 0),
        define_alias("label.fg", Colors::White, 0),
        define_alias("md+hidden", Colors::None, 0),
        define_alias("menu-base.bg", Colors::Black, 0),
        define_alias("month-header.fg", Colors::None, 0),
        define_alias("popup-arrow.fg", Colors::Primary, 0),
        define_alias("popup-base.bg", Colors::Gray, 0),
        define_alias("popup-border.fg", Colors::Primary, 0),
        define_alias("select.bg", Colors::Secondary, 1),
        define_alias("shadow.bg", Colors::Black, 0),
        define_alias("status-base.bg", Colors::Black, 0),
        define_alias("title.bg", Colors::Secondary, 0),
        define_alias("title.fg", Colors::TextDark, 0),
        define_alias("week-header.fg", Colors::Gray, 3),
    ]),
};
