use std::borrow::Cow;
use crate::palette::{Colors, Palette, define_alias};

const DARKNESS: u8 = 64;

/// Radium
/// credits to original radium theme from https://github.com/dharmx
pub const RADIUM_SHELL: Palette = Palette {
    theme_name: Cow::Borrowed("Radium Shell"), 
    theme: Cow::Borrowed("Shell"), 
    name: Cow::Borrowed("Radium"), 
    doc: Cow::Borrowed("credits to original radium theme from https://github.com/dharmx"), 
    generator: Cow::Borrowed("light-dark:64"), 

    color: [
        Palette::interpolate2(0xd4d4d5, 0xffffff, 0x0, 0x0),
        Palette::interpolate2(0x101317, 0x191d22, 0x0, 0x0),
        Palette::interpolate(0x2ba578, 0x37d99e, DARKNESS),
        Palette::interpolate(0x866696, 0xb68acb, DARKNESS),
        Palette::interpolate(0xc4c4c5, 0xaaaaaa, DARKNESS),
        Palette::interpolate(0x101317, 0x191d22, DARKNESS),
        Palette::interpolate(0x3e4145, 0x525559, DARKNESS),
        Palette::interpolate(0xf87070, 0xf87070, DARKNESS),
        Palette::interpolate(0xf0a988, 0xf0a988, DARKNESS),
        Palette::interpolate(0xffe59e, 0xffe59e, DARKNESS),
        Palette::interpolate(0x79dcaa, 0x79dcaa, DARKNESS),
        Palette::interpolate(0x37d99e, 0x37d99e, DARKNESS),
        Palette::interpolate(0x63b3ad, 0x63b3ad, DARKNESS),
        Palette::interpolate(0x50cad2, 0x50cad2, DARKNESS),
        Palette::interpolate(0x7ab0df, 0x7ab0df, DARKNESS),
        Palette::interpolate(0x87bdec, 0x87bdec, DARKNESS),
        Palette::interpolate(0xb68acb, 0xb284c9, DARKNESS),
        Palette::interpolate(0xffa7a7, 0xffb7b7, DARKNESS),
        Palette::interpolate(0xff8e8e, 0xff8e8e, DARKNESS),
    ],
    // must be sorted!
    aliased: Cow::Borrowed(&[
        define_alias("button-base.bg", Colors::White, 3),
        define_alias("container-arrow.fg", Colors::White, 3),
        define_alias("container-base.bg", Colors::None, 0),
        define_alias("container-border.fg", Colors::White, 3),
        define_alias("dialog-arrow.fg", Colors::White, 0),
        define_alias("dialog-base.bg", Colors::None, 0),
        define_alias("dialog-border.fg", Colors::White, 0),
        define_alias("disabled.bg", Colors::Gray, 0),
        define_alias("document-arrow.fg", Colors::White, 3),
        define_alias("document-base.bg", Colors::Black, 0),
        define_alias("document-border.fg", Colors::White, 3),
        define_alias("focus.bg", Colors::Primary, 3),
        define_alias("footer.bg", Colors::None, 0),
        define_alias("footer.fg", Colors::LimeGreen, 0),
        define_alias("header.bg", Colors::None, 0),
        define_alias("header.fg", Colors::LimeGreen, 0),
        define_alias("hover.bg", Colors::Green, 3),
        define_alias("input-focus.bg", Colors::Primary, 3),
        define_alias("input-select.bg", Colors::Secondary, 3),
        define_alias("input.bg", Colors::Gray, 1),
        define_alias("invalid.bg", Colors::Red, 0),
        define_alias("key-binding.bg", Colors::Secondary, 3),
        define_alias("label.fg", Colors::TextLight, 0),
        define_alias("md+hidden", Colors::White, 0),
        define_alias("menu-base.bg", Colors::Black, 1),
        define_alias("month-header.fg", Colors::None, 0),
        define_alias("popup-arrow.fg", Colors::Primary, 3),
        define_alias("popup-base.bg", Colors::Gray, 2),
        define_alias("popup-border.fg", Colors::Primary, 3),
        define_alias("select.bg", Colors::Secondary, 3),
        define_alias("shadow.bg", Colors::Black, 0),
        define_alias("status-base.bg", Colors::Black, 1),
        define_alias("title.bg", Colors::Secondary, 0),
        define_alias("title.fg", Colors::TextLight, 0),
        define_alias("week-header.fg", Colors::BlueGreen, 0),
    ]),
};

