use crate::palette::{Colors, Palette, define_alias};
use std::borrow::Cow;

const DARKNESS: u8 = 64;

/// Rust.
/// A rusty theme. Iron-oxide, Copper-oxide,
/// Cobald-oxide and some Chromium-oxide too.
pub const RUST_SHELL: Palette = Palette {
    theme_name: Cow::Borrowed("Rust Shell"),
    theme: Cow::Borrowed("Shell"),
    name: Cow::Borrowed("Rust"),
    doc: Cow::Borrowed(
        "A rusty theme. Iron-oxide, Copper-oxide,
Cobald-oxide and some Chromium-oxide too.",
    ),
    generator: Cow::Borrowed("light-dark:64"),

    color: [
        Palette::interpolate2(0xd1ccc8, 0xefe6e6, 0x0, 0x0),
        Palette::interpolate2(0x161514, 0x0f0e0d, 0x0, 0x0),
        Palette::interpolate(0x75311a, 0xd25a32, DARKNESS),
        Palette::interpolate(0x77551d, 0xcd9537, DARKNESS),
        Palette::interpolate(0xc4bfbb, 0xede3e3, DARKNESS),
        Palette::interpolate(0x101011, 0x464251, DARKNESS),
        Palette::interpolate(0x726e6b, 0xa39d99, DARKNESS),
        Palette::interpolate(0x75311a, 0xd25a32, DARKNESS),
        Palette::interpolate(0x75431a, 0xd27a32, DARKNESS),
        Palette::interpolate(0x77551d, 0xcd9537, DARKNESS),
        Palette::interpolate(0x44664d, 0x699b76, DARKNESS),
        Palette::interpolate(0x44664d, 0x699b76, DARKNESS),
        Palette::interpolate(0x1a7574, 0x32d2d1, DARKNESS),
        Palette::interpolate(0x1a7574, 0x32d2d1, DARKNESS),
        Palette::interpolate(0x005d94, 0x38b6ff, DARKNESS),
        Palette::interpolate(0x005d94, 0x38b6ff, DARKNESS),
        Palette::interpolate(0x722234, 0xc63f5d, DARKNESS),
        Palette::interpolate(0x7b1964, 0xc62fa3, DARKNESS),
        Palette::interpolate(0x7b1964, 0xd332ad, DARKNESS),
    ],
    // must be sorted!
    aliased: Cow::Borrowed(&[
        define_alias("button-base.bg", Colors::Gray, 0),
        define_alias("container-arrow.fg", Colors::Gray, 0),
        define_alias("container-base.bg", Colors::None, 0),
        define_alias("container-border.fg", Colors::Gray, 0),
        define_alias("dialog-arrow.fg", Colors::White, 0),
        define_alias("dialog-base.bg", Colors::None, 0),
        define_alias("dialog-border.fg", Colors::White, 0),
        define_alias("disabled.bg", Colors::Gray, 3),
        define_alias("document-arrow.fg", Colors::Gray, 0),
        define_alias("document-base.bg", Colors::Black, 0),
        define_alias("document-border.fg", Colors::Gray, 0),
        define_alias("focus.bg", Colors::Primary, 1),
        define_alias("footer.bg", Colors::None, 0),
        define_alias("footer.fg", Colors::Blue, 1),
        define_alias("header.bg", Colors::None, 0),
        define_alias("header.fg", Colors::Blue, 1),
        define_alias("hover.bg", Colors::Blue, 0),
        define_alias("input-focus.bg", Colors::Primary, 1),
        define_alias("input-select.bg", Colors::Secondary, 1),
        define_alias("input.bg", Colors::Gray, 3),
        define_alias("invalid.bg", Colors::Purple, 1),
        define_alias("key-binding.bg", Colors::Secondary, 1),
        define_alias("label.fg", Colors::White, 2),
        define_alias("md+hidden", Colors::None, 0),
        define_alias("menu-base.bg", Colors::Black, 0),
        define_alias("month-header.fg", Colors::None, 0),
        define_alias("popup-arrow.fg", Colors::Primary, 1),
        define_alias("popup-base.bg", Colors::White, 0),
        define_alias("popup-border.fg", Colors::Primary, 1),
        define_alias("select.bg", Colors::Secondary, 1),
        define_alias("shadow.bg", Colors::TextDark, 0),
        define_alias("status-base.bg", Colors::Black, 0),
        define_alias("title.bg", Colors::Primary, 1),
        define_alias("title.fg", Colors::TextLight, 0),
        define_alias("week-header.fg", Colors::Gray, 1),
    ]),
};
