use crate::palette::{Colors, Palette, define_alias};
use std::borrow::Cow;

const DARKNESS: u8 = 63;

/// Blackout.
/// Blackout simulation.
pub const BLACKOUT: Palette = Palette {
    theme_name: Cow::Borrowed("Blackout"),
    theme: Cow::Borrowed("Dark"),
    name: Cow::Borrowed("Blackout"),
    doc: Cow::Borrowed("Blackout simulation."),
    generator: Cow::Borrowed("light-dark:63"),

    color: [
        Palette::interpolate2(0x000000, 0x000000, 0x0, 0x0),
        Palette::interpolate2(0x000000, 0x000000, 0x0, 0x0),
        Palette::interpolate(0x000000, 0x000000, DARKNESS),
        Palette::interpolate(0x000000, 0x000000, DARKNESS),
        Palette::interpolate(0xaaaa00, 0x000000, DARKNESS),
        Palette::interpolate(0x000000, 0x000000, DARKNESS),
        Palette::interpolate(0x000000, 0x000000, DARKNESS),
        Palette::interpolate(0x000000, 0x000000, DARKNESS),
        Palette::interpolate(0x000000, 0x000000, DARKNESS),
        Palette::interpolate(0x000000, 0x000000, DARKNESS),
        Palette::interpolate(0x000000, 0x000000, DARKNESS),
        Palette::interpolate(0x000000, 0x000000, DARKNESS),
        Palette::interpolate(0x000000, 0x000000, DARKNESS),
        Palette::interpolate(0x000000, 0x000000, DARKNESS),
        Palette::interpolate(0x000000, 0x000000, DARKNESS),
        Palette::interpolate(0x000000, 0x000000, DARKNESS),
        Palette::interpolate(0x000000, 0x000000, DARKNESS),
        Palette::interpolate(0x000000, 0x000000, DARKNESS),
        Palette::interpolate(0x000000, 0x000000, DARKNESS),
    ],
    // must be sorted!
    aliased: Cow::Borrowed(&[
        define_alias("button-base.bg", Colors::Black, 0),
        define_alias("container-arrow.fg", Colors::Black, 0),
        define_alias("container-base.bg", Colors::Black, 0),
        define_alias("container-border.fg", Colors::Black, 0),
        define_alias("dialog-arrow.fg", Colors::Black, 0),
        define_alias("dialog-base.bg", Colors::Black, 0),
        define_alias("dialog-border.fg", Colors::Black, 0),
        define_alias("disabled.bg", Colors::Black, 0),
        define_alias("document-arrow.fg", Colors::Black, 0),
        define_alias("document-base.bg", Colors::Black, 0),
        define_alias("document-border.fg", Colors::Black, 0),
        define_alias("focus.bg", Colors::Black, 0),
        define_alias("footer.bg", Colors::Black, 0),
        define_alias("footer.fg", Colors::Black, 0),
        define_alias("header.bg", Colors::Black, 0),
        define_alias("header.fg", Colors::Black, 0),
        define_alias("hover.bg", Colors::Black, 0),
        define_alias("input-focus.bg", Colors::Black, 0),
        define_alias("input-select.bg", Colors::Black, 0),
        define_alias("input.bg", Colors::Black, 0),
        define_alias("invalid.bg", Colors::Black, 0),
        define_alias("key-binding.bg", Colors::Black, 0),
        define_alias("label.fg", Colors::Black, 0),
        define_alias("menu-base.bg", Colors::Black, 0),
        define_alias("month-header.fg", Colors::Black, 0),
        define_alias("popup-arrow.fg", Colors::Black, 0),
        define_alias("popup-base.bg", Colors::Black, 0),
        define_alias("popup-border.fg", Colors::Black, 0),
        define_alias("select.bg", Colors::Black, 0),
        define_alias("shadow.bg", Colors::Black, 0),
        define_alias("status-base.bg", Colors::Black, 0),
        define_alias("title.bg", Colors::Black, 0),
        define_alias("title.fg", Colors::Black, 0),
        define_alias("week-header.fg", Colors::Black, 0),
    ]),
};
