use std::borrow::Cow;
use crate::palette::{Colors, Palette, define_alias};

/// Base16
const DARKNESS: u8 = 64;

pub const BASE16: Palette = Palette {
    theme_name: Cow::Borrowed("Base16"), 
    theme: Cow::Borrowed("Dark"), 
    name: Cow::Borrowed("Base16"), 
    doc: Cow::Borrowed(""), 
    generator: Cow::Borrowed("light-dark:64"), 

    color: [
        Palette::interpolate2(0xaaaaaa, 0xffffff, 0x0, 0x0),
        Palette::interpolate2(0x000000, 0x555555, 0x0, 0x0),
        Palette::interpolate(0x00aaaa, 0x00aaaa, DARKNESS),
        Palette::interpolate(0x00aa00, 0x00aa00, DARKNESS),
        Palette::interpolate(0xaaaaaa, 0xffffff, DARKNESS),
        Palette::interpolate(0x000000, 0x555555, DARKNESS),
        Palette::interpolate(0x555555, 0xaaaaaa, DARKNESS),
        Palette::interpolate(0xaa0000, 0xaa0000, DARKNESS),
        Palette::interpolate(0xaa5500, 0xaa5500, DARKNESS),
        Palette::interpolate(0xffff55, 0xffff55, DARKNESS),
        Palette::interpolate(0x55ff55, 0x55ff55, DARKNESS),
        Palette::interpolate(0x00aa00, 0x00aa00, DARKNESS),
        Palette::interpolate(0x55ffff, 0x55ffff, DARKNESS),
        Palette::interpolate(0x00aaaa, 0x00aaaa, DARKNESS),
        Palette::interpolate(0x5555ff, 0x5555ff, DARKNESS),
        Palette::interpolate(0x0000af, 0x0000af, DARKNESS),
        Palette::interpolate(0xaa00aa, 0xaa00aa, DARKNESS),
        Palette::interpolate(0xff55ff, 0xff55ff, DARKNESS),
        Palette::interpolate(0xff5555, 0xff5a55, DARKNESS),
    ],
    // must be sorted!
    aliased: Cow::Borrowed(&[
        define_alias("button-base.bg", Colors::Gray, 0),
        define_alias("container-arrow.fg", Colors::None, 0),
        define_alias("container-base.bg", Colors::Black, 0),
        define_alias("container-border.fg", Colors::None, 0),
        define_alias("dialog-arrow.fg", Colors::None, 0),
        define_alias("dialog-base.bg", Colors::Gray, 0),
        define_alias("dialog-border.fg", Colors::None, 0),
        define_alias("disabled.bg", Colors::Gray, 3),
        define_alias("document-arrow.fg", Colors::None, 0),
        define_alias("document-base.bg", Colors::Gray, 0),
        define_alias("document-border.fg", Colors::None, 0),
        define_alias("focus.bg", Colors::Primary, 0),
        define_alias("footer.bg", Colors::DeepBlue, 0),
        define_alias("footer.fg", Colors::None, 0),
        define_alias("header.bg", Colors::DeepBlue, 0),
        define_alias("header.fg", Colors::None, 0),
        define_alias("hover.bg", Colors::Secondary, 0),
        define_alias("input-focus.bg", Colors::Primary, 0),
        define_alias("input-select.bg", Colors::Secondary, 0),
        define_alias("input.bg", Colors::Gray, 3),
        define_alias("invalid.bg", Colors::Red, 0),
        define_alias("key-binding.bg", Colors::Orange, 0),
        define_alias("label.fg", Colors::White, 0),
        define_alias("md+hidden", Colors::None, 0),
        define_alias("menu-base.bg", Colors::Black, 0),
        define_alias("month-header.fg", Colors::Gray, 0),
        define_alias("popup-arrow.fg", Colors::None, 0),
        define_alias("popup-base.bg", Colors::White, 0),
        define_alias("popup-border.fg", Colors::None, 0),
        define_alias("select.bg", Colors::Secondary, 0),
        define_alias("shadow.bg", Colors::Black, 0),
        define_alias("status-base.bg", Colors::Black, 0),
        define_alias("title.bg", Colors::Red, 0),
        define_alias("title.fg", Colors::TextLight, 0),
        define_alias("week-header.fg", Colors::Gray, 0),
    ]),
};

