use crate::palette::{Colors, Palette, define_alias};
use std::borrow::Cow;

const DARKNESS: u8 = 63;

/// Falcon
pub const FALCON_DARK: Palette = Palette {
    theme_name: Cow::Borrowed("FalconDark"),
    theme: Cow::Borrowed("Dark"),
    name: Cow::Borrowed("Falcon"),
    doc: Cow::Borrowed(""),
    generator: Cow::Borrowed("light-dark:63"),

    color: [
        Palette::interpolate2(0xdbdbe0, 0xf8f8ff, 0x0, 0x0),
        Palette::interpolate2(0x040411, 0x0c0c2d, 0x0, 0x0),
        Palette::interpolate(0xd17849, 0xff9359, DARKNESS),
        Palette::interpolate(0x6b6ba5, 0x8282ad, DARKNESS),
        Palette::interpolate(0xf8f8ff, 0xf8f8ff, DARKNESS),
        Palette::interpolate(0x0c0c2d, 0x1a1a3a, DARKNESS),
        Palette::interpolate(0x393959, 0x5c5c7c, DARKNESS),
        Palette::interpolate(0xff761a, 0xff761a, DARKNESS),
        Palette::interpolate(0xf99157, 0xf99157, DARKNESS),
        Palette::interpolate(0xffc552, 0xffc552, DARKNESS),
        Palette::interpolate(0xb9e75b, 0xb9e75b, DARKNESS),
        Palette::interpolate(0x9bccbf, 0x9bccbf, DARKNESS),
        Palette::interpolate(0x34bfa4, 0x34bfa4, DARKNESS),
        Palette::interpolate(0xbfdaff, 0xbfdaff, DARKNESS),
        Palette::interpolate(0x6699cc, 0x6699cc, DARKNESS),
        Palette::interpolate(0xa1bce1, 0xa1bce1, DARKNESS),
        Palette::interpolate(0x635196, 0x635196, DARKNESS),
        Palette::interpolate(0xffafb7, 0xffafb7, DARKNESS),
        Palette::interpolate(0xff8e78, 0xff8e78, DARKNESS),
    ],
    // must be sorted!
    aliased: Cow::Borrowed(&[
        define_alias("button-base.bg", Colors::Gray, 0),
        define_alias("container-arrow.fg", Colors::Gray, 1),
        define_alias("container-base.bg", Colors::Black, 0),
        define_alias("container-border.fg", Colors::Gray, 1),
        define_alias("dialog-arrow.fg", Colors::White, 0),
        define_alias("dialog-base.bg", Colors::Black, 3),
        define_alias("dialog-border.fg", Colors::White, 0),
        define_alias("disabled.bg", Colors::Gray, 2),
        define_alias("document-arrow.fg", Colors::Gray, 1),
        define_alias("document-base.bg", Colors::Black, 2),
        define_alias("document-border.fg", Colors::Gray, 1),
        define_alias("focus.bg", Colors::Primary, 0),
        define_alias("footer.bg", Colors::Cyan, 0),
        define_alias("footer.fg", Colors::DeepBlue, 7),
        define_alias("header.bg", Colors::Cyan, 0),
        define_alias("header.fg", Colors::DeepBlue, 7),
        define_alias("hover.bg", Colors::Primary, 3),
        define_alias("input-focus.bg", Colors::Primary, 0),
        define_alias("input-select.bg", Colors::Gray, 3),
        define_alias("input.bg", Colors::Gray, 0),
        define_alias("invalid.bg", Colors::Red, 1),
        define_alias("key-binding.bg", Colors::White, 3),
        define_alias("label.fg", Colors::TextLight, 0),
        define_alias("menu-base.bg", Colors::Black, 3),
        define_alias("month-header.fg", Colors::TextLight, 0),
        define_alias("popup-arrow.fg", Colors::White, 0),
        define_alias("popup-base.bg", Colors::Primary, 1),
        define_alias("popup-border.fg", Colors::White, 0),
        define_alias("select.bg", Colors::Gray, 3),
        define_alias("shadow.bg", Colors::White, 0),
        define_alias("status-base.bg", Colors::Black, 3),
        define_alias("title.bg", Colors::BlueGreen, 1),
        define_alias("title.fg", Colors::Green, 4),
        define_alias("week-header.fg", Colors::TextLight, 3),
    ]),
};
