use crate::palette::{Colors, Palette, define_alias};
use std::borrow::Cow;

const DARKNESS: u8 = 64;

/// Reds.
/// Only red.
pub const REDS: Palette = Palette {
    theme_name: Cow::Borrowed("Reds"),
    theme: Cow::Borrowed("Dark"),
    name: Cow::Borrowed("Reds"),
    doc: Cow::Borrowed("Only red."),
    generator: Cow::Borrowed("light-dark:64"),

    color: [
        Palette::interpolate2(0xcfafaf, 0xe2cfcf, 0x0, 0x0),
        Palette::interpolate2(0x160d0d, 0x3a2323, 0x0, 0x0),
        Palette::interpolate(0xa50000, 0xa55454, DARKNESS),
        Palette::interpolate(0xa52300, 0xa56654, DARKNESS),
        Palette::interpolate(0xcfafaf, 0xe2cfcf, DARKNESS),
        Palette::interpolate(0x160d0d, 0x3a2323, DARKNESS),
        Palette::interpolate(0x6f4343, 0xbd8f8f, DARKNESS),
        Palette::interpolate(0xff7f7f, 0xffcccc, DARKNESS),
        Palette::interpolate(0xff7f7f, 0xffcccc, DARKNESS),
        Palette::interpolate(0xff7f7f, 0xffcccc, DARKNESS),
        Palette::interpolate(0xff7f7f, 0xffcccc, DARKNESS),
        Palette::interpolate(0xff7f7f, 0xffcccc, DARKNESS),
        Palette::interpolate(0xff7f7f, 0xffcccc, DARKNESS),
        Palette::interpolate(0xff7f7f, 0xffcccc, DARKNESS),
        Palette::interpolate(0xff7f7f, 0xffcccc, DARKNESS),
        Palette::interpolate(0xff7f7f, 0xffcccc, DARKNESS),
        Palette::interpolate(0xff7f7f, 0xffcccc, DARKNESS),
        Palette::interpolate(0xff7f7f, 0xffcccc, DARKNESS),
        Palette::interpolate(0xff7f7f, 0xffcccc, DARKNESS),
    ],
    // must be sorted!
    aliased: Cow::Borrowed(&[
        define_alias("button-base.bg", Colors::Gray, 0),
        define_alias("container-arrow.fg", Colors::None, 0),
        define_alias("container-base.bg", Colors::Black, 1),
        define_alias("container-border.fg", Colors::None, 0),
        define_alias("dialog-arrow.fg", Colors::None, 0),
        define_alias("dialog-base.bg", Colors::Gray, 2),
        define_alias("dialog-border.fg", Colors::None, 0),
        define_alias("disabled.bg", Colors::Gray, 3),
        define_alias("document-arrow.fg", Colors::None, 0),
        define_alias("document-base.bg", Colors::Black, 2),
        define_alias("document-border.fg", Colors::None, 0),
        define_alias("focus.bg", Colors::Primary, 1),
        define_alias("footer.bg", Colors::Black, 1),
        define_alias("footer.fg", Colors::Blue, 2),
        define_alias("header.bg", Colors::Black, 1),
        define_alias("header.fg", Colors::Blue, 2),
        define_alias("hover.bg", Colors::Secondary, 1),
        define_alias("input-focus.bg", Colors::Primary, 1),
        define_alias("input-select.bg", Colors::Secondary, 1),
        define_alias("input.bg", Colors::Gray, 2),
        define_alias("invalid.bg", Colors::Red, 1),
        define_alias("key-binding.bg", Colors::BlueGreen, 0),
        define_alias("label.fg", Colors::White, 0),
        define_alias("md+hidden", Colors::None, 0),
        define_alias("menu-base.bg", Colors::Black, 0),
        define_alias("month-header.fg", Colors::None, 0),
        define_alias("popup-arrow.fg", Colors::None, 0),
        define_alias("popup-base.bg", Colors::Gray, 1),
        define_alias("popup-border.fg", Colors::None, 0),
        define_alias("select.bg", Colors::Secondary, 3),
        define_alias("shadow.bg", Colors::None, 0),
        define_alias("status-base.bg", Colors::Black, 0),
        define_alias("title.bg", Colors::Red, 0),
        define_alias("title.fg", Colors::TextDark, 0),
        define_alias("week-header.fg", Colors::None, 0),
    ]),
};
