use crate::palette::{Colors, Palette, define_alias};
use std::borrow::Cow;

const DARKNESS: u8 = 64;

/// Tundra.
/// A frozen theme. Long exposure causes snow-blindness.
pub const TUNDRA: Palette = Palette {
    theme_name: Cow::Borrowed("Tundra"),
    theme: Cow::Borrowed("Dark"),
    name: Cow::Borrowed("Tundra"),
    doc: Cow::Borrowed("A frozen theme. Long exposure causes snow-blindness."),
    generator: Cow::Borrowed("light-dark:64"),

    color: [
        Palette::interpolate2(0xe6eaf2, 0xffffff, 0x0, 0x0),
        Palette::interpolate2(0x0b1221, 0x1a2130, 0x0, 0x0),
        Palette::interpolate(0xe6eaf2, 0xffffff, DARKNESS),
        Palette::interpolate(0xa8bbd4, 0x719bd3, DARKNESS),
        Palette::interpolate(0xe6eaf2, 0xffffff, DARKNESS),
        Palette::interpolate(0x10151e, 0x1d2535, DARKNESS),
        Palette::interpolate(0x424751, 0x6c7484, DARKNESS),
        Palette::interpolate(0xf9c7c7, 0xfca5a5, DARKNESS),
        Palette::interpolate(0xf9dac7, 0xfbc19d, DARKNESS),
        Palette::interpolate(0xe5d5b7, 0xe5c690, DARKNESS),
        Palette::interpolate(0xbce5b7, 0x99e590, DARKNESS),
        Palette::interpolate(0xbce5b7, 0x99e590, DARKNESS),
        Palette::interpolate(0xa8bbd4, 0x83a5d1, DARKNESS),
        Palette::interpolate(0xc8eafc, 0x9fddfc, DARKNESS),
        Palette::interpolate(0xc7d1f9, 0x9daef9, DARKNESS),
        Palette::interpolate(0xbfcaef, 0x97a7ef, DARKNESS),
        Palette::interpolate(0xb8add8, 0x9c88d8, DARKNESS),
        Palette::interpolate(0xffcccc, 0xf79b9b, DARKNESS),
        Palette::interpolate(0xf9c7ce, 0xfc9fab, DARKNESS),
    ],
    // must be sorted!
    aliased: Cow::Borrowed(&[
        define_alias("button-base.bg", Colors::Gray, 0),
        define_alias("container-arrow.fg", Colors::None, 0),
        define_alias("container-base.bg", Colors::Black, 3),
        define_alias("container-border.fg", Colors::None, 0),
        define_alias("dialog-arrow.fg", Colors::None, 0),
        define_alias("dialog-base.bg", Colors::Gray, 2),
        define_alias("dialog-border.fg", Colors::None, 0),
        define_alias("disabled.bg", Colors::Gray, 3),
        define_alias("document-arrow.fg", Colors::None, 0),
        define_alias("document-base.bg", Colors::Black, 2),
        define_alias("document-border.fg", Colors::None, 0),
        define_alias("focus.bg", Colors::Primary, 1),
        define_alias("footer.bg", Colors::BlueGreen, 2),
        define_alias("footer.fg", Colors::TextDark, 0),
        define_alias("header.bg", Colors::BlueGreen, 3),
        define_alias("header.fg", Colors::TextDark, 0),
        define_alias("hover.bg", Colors::Secondary, 0),
        define_alias("input-focus.bg", Colors::Primary, 1),
        define_alias("input-select.bg", Colors::Secondary, 1),
        define_alias("input.bg", Colors::Gray, 3),
        define_alias("invalid.bg", Colors::Red, 3),
        define_alias("key-binding.bg", Colors::BlueGreen, 0),
        define_alias("label.fg", Colors::White, 0),
        define_alias("md+hidden", Colors::None, 0),
        define_alias("menu-base.bg", Colors::Black, 1),
        define_alias("month-header.fg", Colors::None, 0),
        define_alias("popup-arrow.fg", Colors::None, 0),
        define_alias("popup-base.bg", Colors::White, 0),
        define_alias("popup-border.fg", Colors::None, 0),
        define_alias("select.bg", Colors::Secondary, 1),
        define_alias("shadow.bg", Colors::TextDark, 0),
        define_alias("status-base.bg", Colors::Black, 1),
        define_alias("title.bg", Colors::BlueGreen, 3),
        define_alias("title.fg", Colors::TextDark, 0),
        define_alias("week-header.fg", Colors::BlueGreen, 0),
    ]),
};
