use crate::{ColorIdx, Colors, Palette};

/// EverForest
const DARKNESS: u8 = 86;

pub const EVERFOREST: Palette = Palette {
    name: "EverForest", 

    color: [
        Palette::interpolate2(0xd8d4cb, 0xfcf8ef, 0x0, 0x0),
        Palette::interpolate2(0x090a09, 0x2c2d2a, 0x0, 0x0),
        Palette::interpolate(0x69a59d, 0x69a59d, DARKNESS),
        Palette::interpolate(0x7393b3, 0x7393b3, DARKNESS),
        Palette::interpolate(0xd3c6ab, 0xc4ac7b, DARKNESS),
        Palette::interpolate(0x272f35, 0x30383d, DARKNESS),
        Palette::interpolate(0x4e565c, 0x656d73, DARKNESS),
        Palette::interpolate(0xe67e80, 0xfc8f93, DARKNESS),
        Palette::interpolate(0xe69875, 0xf4ab8b, DARKNESS),
        Palette::interpolate(0xdbbc7f, 0xddc187, DARKNESS),
        Palette::interpolate(0xa7c080, 0xb8ce94, DARKNESS),
        Palette::interpolate(0x83c092, 0x83c092, DARKNESS),
        Palette::interpolate(0x69a59d, 0x77ada6, DARKNESS),
        Palette::interpolate(0x95d1c9, 0xafdbd5, DARKNESS),
        Palette::interpolate(0x7393b3, 0x8fa7bf, DARKNESS),
        Palette::interpolate(0x78b4ac, 0x8dc4bd, DARKNESS),
        Palette::interpolate(0xd699b6, 0xe5b7cd, DARKNESS),
        Palette::interpolate(0xff75a0, 0xf5608e, DARKNESS),
        Palette::interpolate(0xce8196, 0xbf7082, DARKNESS),
    ],
    // must be sorted!
    aliased: &[
        ("button-base", ColorIdx(Colors::Green, 4)),
        ("container-arrow", ColorIdx(Colors::Gray, 1)),
        ("container-base", ColorIdx(Colors::White, 3)),
        ("container-border", ColorIdx(Colors::Gray, 1)),
        ("dialog-arrow", ColorIdx(Colors::Gray, 1)),
        ("dialog-base", ColorIdx(Colors::White, 0)),
        ("dialog-border", ColorIdx(Colors::Gray, 1)),
        ("disabled", ColorIdx(Colors::Gray, 2)),
        ("focus", ColorIdx(Colors::Primary, 3)),
        ("footer", ColorIdx(Colors::None, 0)),
        ("footer-fg", ColorIdx(Colors::DeepBlue, 7)),
        ("header", ColorIdx(Colors::None, 0)),
        ("header-fg", ColorIdx(Colors::DeepBlue, 7)),
        ("hover", ColorIdx(Colors::DeepBlue, 0)),
        ("input", ColorIdx(Colors::White, 0)),
        ("invalid", ColorIdx(Colors::Red, 1)),
        ("key-binding", ColorIdx(Colors::Green, 0)),
        ("label", ColorIdx(Colors::TextDark, 1)),
        ("menu-base", ColorIdx(Colors::White, 3)),
        ("month-header-fg", ColorIdx(Colors::None, 0)),
        ("popup-arrow", ColorIdx(Colors::Gray, 3)),
        ("popup-base", ColorIdx(Colors::White, 2)),
        ("popup-border", ColorIdx(Colors::Gray, 3)),
        ("select", ColorIdx(Colors::Secondary, 1)),
        ("shadows", ColorIdx(Colors::Black, 0)),
        ("status-base", ColorIdx(Colors::White, 3)),
        ("text-focus", ColorIdx(Colors::Primary, 3)),
        ("text-select", ColorIdx(Colors::Secondary, 1)),
        ("title", ColorIdx(Colors::None, 0)),
        ("title-fg", ColorIdx(Colors::Magenta, 0)),
        ("week-header-fg", ColorIdx(Colors::Gray, 3)),
    ],
};

