//!
//! Some helper functions that can calculate special layouts.
//!
use ratatui::layout::{Constraint, Direction, Flex, Layout, Margin, Rect};
use std::cmp::max;

/// Constraint data for [layout_edit]
#[derive(Debug)]
pub enum EditConstraint<'a> {
    Label(&'a str),
    Widget(u16),
}

/// Layout generated by [layout_edit]
#[derive(Debug, Default)]
pub struct LayoutEdit {
    pub label: Vec<Rect>,
    pub widget: Vec<Rect>,
}

/// Simple layout for an edit mask.
/// It creates one column of input widgets and aligns the labels.
pub fn layout_edit<const N: usize>(area: Rect, constraints: [EditConstraint<'_>; N]) -> LayoutEdit {
    let mut max_width = 0;
    for l in constraints.iter() {
        match l {
            EditConstraint::Label(s) => {
                max_width = max(max_width, s.len() as u16);
            }
            EditConstraint::Widget(_) => {}
        }
    }

    let mut result = LayoutEdit::default();

    let mut x = area.x;
    let mut y = area.y;
    for l in constraints.iter() {
        match l {
            EditConstraint::Label(_) => {
                result.label.push(Rect::new(x, y, max_width, 1));
                x += max_width + 1;
            }
            EditConstraint::Widget(w) => {
                result.widget.push(Rect::new(x, y, *w, 1));
                x = area.x;
                y += 1;
            }
        };
    }

    result
}

/// Layout produced by [layout_dialog]
#[derive(Debug)]
pub struct LayoutDialog<const N: usize> {
    pub dialog: Rect,
    pub area: Rect,
    pub button_area: Rect,
    pub buttons: [Rect; N],
}

/// Calculates a layout for a dialog with buttons.
pub fn layout_dialog<const N: usize>(
    area: Rect,
    h_constraint: Constraint,
    v_constraint: Constraint,
    insets: Margin,
    buttons: [Constraint; N],
    button_spacing: u16,
    button_flex: Flex,
) -> LayoutDialog<N> {
    let l_vertical = Layout::new(
        Direction::Vertical,
        [Constraint::Fill(1), v_constraint, Constraint::Fill(1)],
    )
    .split(area);
    let l_dialog = Layout::new(
        Direction::Horizontal,
        [Constraint::Fill(1), h_constraint, Constraint::Fill(1)],
    )
    .split(l_vertical[1])[1];

    let l_inner = l_dialog.inner(&insets);

    let l_content = Layout::vertical([
        Constraint::Fill(1),
        Constraint::Length(insets.vertical),
        Constraint::Length(1),
    ])
    .split(l_inner);

    let l_buttons = Layout::horizontal(buttons)
        .spacing(button_spacing)
        .flex(button_flex)
        .areas(l_content[2]);

    LayoutDialog {
        dialog: l_dialog,
        area: l_inner,
        button_area: l_content[2],
        buttons: l_buttons,
    }
}
